local ID = require("scripts/zones/Upper_Jeuno/IDs")

return {
    ['_6s2']         = { event = 116 },
    ['_6sb']         = { text = ID.text.IT_READS_STAFF_ONLY },
    ['Artush']       = { event = 42 },
    ['Baudin']       = { event = 122 },
    ['Chocobo']      = { event = 62 },
    ['ChocoboA']     = { event = 54 },
    ['ChocoboB']     = { event = 56 },
    ['Collet']       = { event = 114 },
    ['Constance']    = { event = 90 },
    ['Guide_Stone']  = { messageSpecial = ID.text.GUIDE_STONE },
    ['Ilumida']      = { event = 189 },
    ['Laila']        = { event = 10120 },
    ['Mailloquetat'] = { event = 25 },
    ['Mapitoto']     = { event = 10222 },
    ['Nevela']       = { event = 69 },
    ['Monberaux']    = { event = 28 },
    ['Olgald']       = { event = 10122 },
    ['Osker']        = { event = 50 },
    ['Paya-Sabya']   = { event = 79 },
    ['Rhea_Myuliah'] = { event = 10121 },
    ['Rosaline']     = { event = 96 },
    ['Rouliette']    = { event = 30 },
    ['Shalott']      = { event = 104 },
    ['Souren']       = { event = 88 },
    ['Zuber']        = { event = 125 },
}
