local ID = require("scripts/zones/Northern_San_dOria/IDs")

return {
    ['Abeaule']       = { text = ID.text.ABEAULE_DIALOG_THANKS },
    ['Ailbeche']      = { event = 868 },
    ['Aivedoir']      = { text = ID.text.AIVEDOIR_DIALOG },
    ['Arienh']        = { text = ID.text.ARIENH_DIALOG },
    ['Charlaimagnat'] = { event = 702 },
    ['Chasalvige']    = { event = 6 },
    ['Emilia']        = { text = ID.text.EMILIA_DIALOG },
    ['Eperdur']       = { event = 678 },
    ['Fittesegat']    = { text = ID.text.FITTESEGAT_DIALOG },
    ['Gilipese']      = { text = ID.text.GILIPESE_DIALOG },
    ['Guilerme']      = { text = ID.text.GUILERME_DIALOG },
    ['Helaku']        = { event = 541 },
    ['Hinaree']       = { event = 580 },
    ['Ishwar']        = { text = ID.text.ISHWAR_DIALOG },
    ['Kasaroro']      = { event = 548 },
    ['Malfine']       = { text = ID.text.MALFINE_DIALOG },
    ['Maurine']       = { text = ID.text.MAURINE_DIALOG },  -- NOTE: These are two different NPCs
    ['Maurinne']      = { text = ID.text.MAURINNE_DIALOG },
    ['Miageau']       = { event = 517 },
    ['Nouveil']       = { event = 574 },
    ['Pellimie']      = { text = ID.text.PELLIMIE_DIALOG },
    ['Pepigort']      = { text = ID.text.PEPIGORT_DIALOG },
    ['Phaviane']      = { text = ID.text.PHAVIANE_DIALOG },
    ['Prerivon']      = { text = ID.text.PRERIVON_DIALOG },
    ['Rodaillece']    = { text = ID.text.RODAILLECE_DIALOG },
    ['Sochiene']      = { text = ID.text.SOCHIENE_DIALOG },
}
