local ID = zones[xi.zone.NORTHERN_SAN_DORIA]

return {
    ['_6fc']              = { messageSpecial = ID.text.ITS_LOCKED }, -- Door Papal Chambers
    ['Abeaule']           = { text = ID.text.ABEAULE_DIALOG_THANKS },
    ['Abioleget']         = { text = ID.text.ABIOLEGET_DIALOG },
    ['Ailbeche']          = { event = 868 },
    ['Aivedoir']          = { text = ID.text.AIVEDOIR_DIALOG },
    ['Anieuvansand']      = { event = 665 },
    ['Arienh']            = { text = ID.text.ARIENH_DIALOG },
    ['Arnau']             = { event =  20 }, -- TODO: CS 520 default while RoV M1-3 active?
    ['Bacherume']         = { text = ID.text.YOU_STAND_BEFORE },
    ['Belgidiveau']       = { event = 585 },
    ['Calovour']          = { event = 633 },
    ['Capiria']           = { text = ID.text.CAPIRIA_DIALOG },
    ['Charlaimagnat']     = { event = 702 },
    ['Charmealaut']       = { event = 768 },
    ['Chasalvige']        = { event =   6 },
    ['Coullene']          = { text = ID.text.COULLENE_DIALOG },
    ['Danngogg']          = { event = 540 },
    ['Dapraugeant']       = { event = 532 },
    ['Daveille']          = { event = 584 },
    ['Emilia']            = { text = ID.text.EMILIA_DIALOG },
    ['Eperdur']           = { event = 678 },
    ['Esqualea']          = { event = 670 },
    ['Fantarviont']       = { event = 671 },
    ['Fittesegat']        = { text = ID.text.FITTESEGAT_DIALOG },
    ['Galahad']           = { text = ID.text.GALAHAD_DIALOG },
    ['Gilipese']          = { text = ID.text.GILIPESE_DIALOG },
    ['Guilerme']          = { text = ID.text.GUILERME_DIALOG },
    ['Halaviabeau']       = { event = 611 },
    ['Helaku']            = { event = 541 },
    ['Hinaree']           = { event = 580 },
    ['Icoua']             = { event = 674 },
    ['Ishwar']            = { text = ID.text.ISHWAR_DIALOG },
    ['Jufaue']            = { event = 715 },
    ['Kasaroro']          = { event = 548 },
    ['Letterare']         = { event = 660 },
    ['Machella']          = { event = 672 },
    ['Malfine']           = { text = ID.text.MALFINE_DIALOG },
    ['Matildie']          = { event = 587 },
    ['Maurine']           = { text = ID.text.MAURINE_DIALOG },  -- NOTE: These are two different NPCs
    ['Maurinne']          = { text = ID.text.MAURINNE_DIALOG },
    ['Mevaloud']          = { event = 661 },
    ['Miageau']           = { event = 517 },
    ['Morjean']           = { event = 601 },
    ['Morunaude']         = { event = 634 },
    ['Narcheral']         = { event = 688 },
    ['Narsaude']          = { event = 668 },
    ['Nouveil']           = { event = 574 },
    ['Odyssean_Passage']  = { messageSpecial = ID.text.NOTHING_HAPPENS },
    ['Pala_Korin']        = { event = 555 },
    ['Pellimie']          = { text = ID.text.PELLIMIE_DIALOG },
    ['Pepigort']          = { text = ID.text.PEPIGORT_DIALOG },
    ['Phaviane']          = { text = ID.text.PHAVIANE_DIALOG },
    ['Pikiki']            = { event = 553 },
    ['Pontaudarme']       = { event = 717 },
    ['Prerivon']          = { text = ID.text.PRERIVON_DIALOG },
    ['Pursuivant']        = { event = 760 },
    ['Rodaillece']        = { text = ID.text.RODAILLECE_DIALOG },
    ['Rondipur']          = { event = 721 },
    ['Ronpaurege']        = { event = 669 },
    ['Secodiand']         = { event =  17 },
    ['Shakir']            = { event = 538 },
    ['Sochiene']          = { text = ID.text.SOCHIENE_DIALOG },
    ['Suspicious_Elvaan'] = { event = 881 },
    ['Synergy_Engineer']  = { event = 11002 },
    ['Taurette']          = { event =   664 },
    ['Vamorcote']         = { event =   651 },
    ['Vavegallet']        = { event =   673 },
    ['Villion']           = { event =   632 },
}
