-- Intentionally blank file
--
-- This file exists solely to appear at the top of files that use settings as:
--
-- require('scripts/globals/settings')
--
-- As a visual indication that "settings are being used in this file somewhere".
--
-- Settings are loaded during executable startup, and then published into the
-- Lua state.
--
-- Settings files in <root>/settings/default/ are loaded first.
-- Then if any files exist in <root>/settings/, they are read and their values
-- are used to overwrite the values from the defaults folder (if there are any
-- values).
