local ID = zones[xi.zone.SOUTHERN_SAN_DORIA]

return {
    ['Adaunel']              = { event = 656 },
    ['Amaura']               = { event = 642 },
    ['Anxaberoute']          = { event = 886 },
    ['Arpetion']             = { event = 660 },
    ['Atelloune']            = { event = 884 },
    ['Aubejart']             = { event = 582 },
    ['Balasiel']             = { event = 667 },
    ['Baunise']              = { text = ID.text.NOTHING_TO_REPORT },
    ['Cahaurme']             = { text = ID.text.NOTHING_TO_REPORT },
    ['Ceraule']              = { event = 509 },
    ['Chocobo']              = { event = 818 }, -- TODO: Verify all chocobos use the same event
    ['Chocobo_1']            = { event = 818 },
    ['Chocobo_2']            = { event = 818 },
    ['Chocobo_3']            = { event = 818 },
    ['Clainomille']          = { event = 613 },
    ['Coderiant']            = { event = 583 },
    ['Collione']             = { event = 859 },
    ['Enigmatic Footprints'] = { messageSpecial = ID.text.TEAR_IN_FABRIC_OF_SPACE },
    ['Ephauge']              = { event = 581 },
    ['Esmallegue']           = { event = 885 },
    ['Estiliphire']          = { event = 897 },
    ['Exoroche']             = { event =  76 },
    ['Femitte']              = { event = 661 },
    ['Foletta']              = { event = 666 },
    ['Fulchia']              = { event = 587 },
    ['Gizel']                = { event = 676 },
    ['Guilboire']            = { event = 657 },
    ['Hae_Jakhya']           = { event = 610 },
    ['Helbort']              = { text = ID.text.HELBORT_DIALOG },
    ['Katharina']            = { event = 887 },
    ['Lotte']                = { event = 564 },
    ['Luthiaque']            = { event = 658 },
    ['Maugie']               = { event =  46 },
    ['Melledanne']           = { event = 943 },
    ['Ophelia']              = { event = 751 },
    ['Paouala']              = { event =  82 },
    ['Phillone']             = { event =  29 },
    ['Poudoruchant']         = { event = 779 },
    ['qm2']                  = { messageSpecial = ID.text.NOTHING_OUT_OF_ORDINARY },
    ['qm4']                  = { messageSpecial = ID.text.NOTHING_OUT_OF_ORDINARY },
    ['Rosel']                = { text = ID.text.ROSEL_GREETINGS },
    ['Rouva']                = { event = 662 },
    ['Rumoie']               = { event = 863 },
    ['Simmie']               = { event = 673 },
    ['Sobane']               = { text = ID.text.SOBANE_DIALOG },
    ['Taumila']              = { text = ID.text.TAUMILA_DIALOG },
    ['Valderotaux']          = { event = 58 },
}
