local ID = zones[xi.zone.KAZHAM]

return {
    ['_6y9']              = { event = 126 },
    ['Balih_Chavizaai']   = { event = 40 },
    ['Beyzen']            = { event = 278 },
    ['Bhi_Telifahgo']     = { event = 93 },
    ['Bhukka_Sahbeo']     = { event = 122 },
    ['Bubupp']            = { text = ID.text.OPO_OPO },
    ['Cha_Tigunalhgo']    = { event = 100 },
    ['Cobbi_Malgharam']   = { event = 41 },
    ['Coyah_Neblahe']     = { event = 156 },
    ['Dheo_Nbolo']        = { event = 91 },
    ['Dodmos']            = { event = 275 },
    ['Etteh_Sulaej']      = { event = 42 },
    ['Ghosa_Demuhzo']     = { event = 87 },
    ['Haih_Ahmpagako']    = { event = 62 },
    ['Hari_Pakhroib']     = { event = 84 },
    ['Hildegard']         = { event = 312 },
    ['Hozie_Naharaf']     = { event = 89 },
    ['Jakoh_Wahcondalo']  = { event = 113 },
    ['Kakapp']            = { text = ID.text.OPO_OPO },
    ['Khaffi_Salponoihz'] = { event = 83 },
    ['Khau_Mahiyoeloh']   = { event = 60 },
    ['Kocho_Phunakcham']  = { event = 65 },
    ['Kukupp']            = { text = ID.text.OPO_OPO },
    ['Kyun_Magopiteh']    = { event = 86 },
    ['Lulupp']            = { text = ID.text.OPO_OPO },
    ['Mhebi_Juhbily']     = { event = 125 },
    ['Mijeh_Sholpoilo']   = { event = 63 },
    ['Mitti_Haplihza']    = { event = 94 },
    ['Mumupp']            = { text = ID.text.OPO_OPO },
    ['Nenepp']            = { text = ID.text.OPO_OPO },
    ['Nti_Badolsoma']     = { event = 88 },
    ['Pofhu_Tendelicon']  = { event = 64 },
    ['Popopp']            = { text = ID.text.OPO_OPO },
    ['Pula_Rhatti']       = { event = 92 },
    ['Qhio_Plittibhi']    = { event = 154 },
    ['Romaa_Mihgo']       = { event = 263 },
    ['Roropp']            = { text = ID.text.OPO_OPO },
    ['Soun_Abralah']      = { event = 101 },
    ['Swift']             = { text = ID.text.SUSPICIOUS_CHARACTERS }, -- TODO: Confirm old event was for quest "A Discerning Eye"
    ['Tatapp']            = { text = ID.text.OPO_OPO },
    ['Thali_Mhobrum']     = { event = 190 },
    ['Tio_Moshroca']      = { event = 123 },
    ['Toeh_Leddenbah']    = { event = 85 },
    ['Tsahbi_Ifalombo']   = { event = 90 },
    ['Tsui_Golalapahn']   = { event = 61 },
    ['Vah_Keshura']       = { event = 124 },
    ['Vanono']            = { event = 262 },
}
