local ID = require('scripts/zones/Bastok_Markets/IDs')

return {
    ['Alert_Gaze']  = { event = 131 },
    ['Angry_Bull']  = { event = 472 },
    ['Anguysh']     = { event = 135 },
    ['Aquillina']   = { event = 116 },
    ['Arawn']       = { event = 114 },
    ['Ardea']       = { event = 260 },
    ['Big_Harvest'] = { event = 134 },
    ['Biggorf']     = { event = 126 },
    ['Brygid']      = { event = 119 },
    ['Degenhard']   = { event = 255 },
    ['Domhnall']    = { event = 117 },
    ['Emrys']       = { event = 115 },
    ['Enu']         = { event = 327 },
    ['Epione']      = { event = 130 },
    ['Foss']        = { event = 270 },
    ['Gwill']       = { event = 113 },
    ['Hildith']     = { event = 488 },
    ['Horatius']    = { event = 110 },
    ['Julio']       = { event = 275 },
    ['Ken']         = { event = 361 },
    ['Lame_Deer']   = { event = 129 },
    ['Lavinia']     = { event = 123 },
    ['Loulia']      = { event = 487 },
    ['Marin']       = { event = 361 },
    ['Matthias']    = { event = 499 },
    ['Michea']      = { event = 125 },
    ['Nbu_Latteh']  = { event = 127 },
    ['Nudara']      = { event = 118 },
    ['Offa']        = { event = 124 },
    ['Parnika']     = { event = 136 },
    ['Pavel']       = { event = 128 },
    ['Red_Canyon']  = { event = 133 },
    ['Rock_Jaw']    = { event = 325 },
    ['Samia']       = { event = 111 },
    ['Shamarhaan']  = { event = 433 },
    ['Tancredi']    = { event = 132 },
    ['Tanguy']      = { event = 120 },
    ['Umberto']     = { event = 411 },
    ['Zacc']        = { event = 328 },
    ['Zon-Fobun']   = { event = 250 },
}
