require("scripts/globals/zone")
local list =
{
    [xi.zone.DYNAMIS_BASTOK] =
    {
        -- Normal Quadav Mobs
    { "Adamantking Eff", "Adamantking Effigy" },
    { "Adamantking Img", "Adamantking Image" },
    { "Eff. Prototype", "Effigy Prototype" },
    { "V. Vindicator", "Vanguard Vindicator" },
    { "V. Militant", "Vanguard Militant" },
    { "V. Constable", "Vanguard Constable" },
    { "V. Thaumaturge", "Vanguard Thaumaturge" },
    { "V. Protector", "Vanguard Protector" },
    { "V. Purloiner", "Vanguard Purloiner" },
    { "V. Defender", "Vanguard Defender" },
    { "V. Vigilante", "Vanguard Vigilante" },
    { "V. Beasttender", "Vanguard Beasttender" },
    { "V. Minstrel", "Vanguard Minstrel" },
    { "V. Mason", "Vanguard Mason" },
    { "V. Hatamoto", "Vanguard Hatamoto" },
    { "V. Kusa", "Vanguard Kusa" },
    { "V. Drakekeeper", "Vanguard Drakekeeper" },
    { "V. Undertaker", "Vanguard Undertaker" },
        -- Bastok Specific Mobs
    { "A.Dismantler", "Aa'Nyu Dismantler" },
    { "G.Noondozer", "Gu'Nhi Noondozer" },
    { "B.Tortoisedriver", "Be'Ebo Tortoisedriver" },
    { "G.Manameister", "Gi'Pha Manameister" },
    { "K.Cannonball", "Ko'Dho Cannonball" },
    { "Z.Fallsplitter", "Ze'Vho Fallsplitter" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_SAN_DORIA] =
    {
        -- Normal Orc Mobs
    { "Serj. Tombstone", "Sergeant Tombstone" },
    { "War. Tombstone", "Warchief Tombstone" },
    { "Tomb. Prototype", "Tombstone Prototype" },
    { "V. Footsoldier", "Vanguard Footsoldier" },
    { "V. Grappler", "Vanguard Grappler" },
    { "V. Amputator", "Vanguard Amputator" },
    { "V. Mesmerizer", "Vanguard Mesmerizer" },
    { "V. Vexer", "Vanguard Vexer" },
    { "V. Pillager", "Vanguard Pillager" },
    { "V. Trooper", "Vanguard Trooper" },
    { "V. Neckchopper", "Vanguard Neckchopper" },
    { "V. Hawker", "Vanguard Hawker" },
    { "V. Bugler", "Vanguard Bugler" },
    { "V. Predator", "Vanguard Predator" },
    { "V. Gutslasher", "Vanguard Gutslaher" },
    { "V. Backstabber", "Vanguard Backstabber" },
    { "V. Impaler", "Vanguard Impaler" },
    { "V. Dollmaster", "Vanguard Dollmaster" },
        -- San d'Oria Specific Mobs
    { "W.Bjadek", "Wyrmgnasher Bjakdek" },
    { "R.Gadgquok", "Reapertongue Gadgquok" },
    { "V.Butchnotch", "Voidstreaker Butchnotch" },
    { "B.Glitchfotch", "Battlechoice Gitchfotch" },
    { "S.Fugbrag", "Soulsender Fugbrag" },
    { "O. Tombstone", "Overlord's Tombstone" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_WINDURST] =
    {
        -- Normal Yagudo Mobs
    { "V. Skirmisher", "Vanguard Skirmisher" },
    { "V. Sentinel", "Vanguard Sentinel" },
    { "V. Priest", "Vanguard Priest" },
    { "V. Prelate", "Vanguard Prelate" },
    { "V. Visionary", "Vanguard Visionary" },
    { "V. Liberator", "Vanguard Liberator" },
    { "V. Exemplar", "Vanguard Exemplar" },
    { "V. Inciter", "Vanguard Inciter" },
    { "V. Ogresoother", "Vanguard Ogresoother" },
    { "V. Chanter", "Vanguard Chanter" },
    { "V. Salvager", "Vanguard Salvager" },
    { "V. Persecutor", "Vanguard Persecutor" },
    { "V. Assassin", "Vanguard Assassin" },
    { "V. Partisan", "Vanguard Partisan" },
    { "V. Oracle", "Vanguard Oracle" },
        -- Windurst Specific Mobs
    { "X.Solemn", "Xoo Kaza the Solemn" },
    { "H.Stentorian", "Haa Pevi the Stentorian" },
    { "W.Razorclaw", "Wuu Qoho the Razorclaw" },
    { " L.Eyepiercer", "Loo Hepe the Eyepiercer" },
    { "Muu.Steadfast", "Muu Febi the Steadfast" },
    { "Maa.Steadfast", "Maa Febi the Steadfast" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_JEUNO] =
    {
        -- Normal Goblin Mobs
    { "Stat. Prototype", "Statue Prototype" },
    { "V. Smithy", "Vanguard Smithy" },
    { "V. Pitfighter", "Vanguard Pitfighter" },
    { "V. Alchemist", "Vanguard Alchemist" },
    { "V. Shaman", "Vanguard Shaman" },
    { "V. Enchanter", "Vanguard Enchanter" },
    { "V. Welldigger", "Vanguard Welldigger" },
    { "V. Armorer", "Vanguard Armorer" },
    { "V. Tinkerer", "Vanguard Tinkerer" },
    { "V. Pathfinder", "Vanguard Pathfinder" },
    { "V. Maestro", "Vanguard Maestro" },
    { "V. Ambusher", "Vanguard Ambusher" },
    { "V. Ronin", "Vanguard Ronin" },
    { "V. Hitman", "Vanguard Hitman" },
    { "V. Dragontamer", "Vanguard Dragontamer" },
    { "V. Necromancer", "Vanguard Necromancer" },
        -- Jeuno Specific Mobs
    { "B.Rockjaw", "Bandrix Rockjaw" },
    { "B.Eargone", "Buffrix Eargone" },
    { "C.Longnail", "Clocktix Longnail" },
    { "E.Hooknose", "Elixmix Hooknose " },
    { "G.Magpietongue", "Gabblox Magpietongue" },
    { "H.Toothrot", "Hermitrix Toothrot" },
    { "H.Drumbelly", "Humnox Drumbelly " },
    { "L.Dhalmelneck", "Lurklox Dhalmelneck" },
    { "M.Moldnoggin", "Morgmox Moldnoggin" },
    { "S.Sweatbrow", "Sparkspox Sweatbrow" },
    { "T.Beadeyes", "Ticktox Beadeyes" },
    { "T.Goatmug", "Trailblix Goatmug" },
    { "T.Loglimbs", "Tufflix Loglimbs" },
    { "W.Snakespecs", "Wyrmwix Snakespecs" },
    { "K.Swollenskull", "Karashix Swollenskull" },
    { "K.Longlegs", "Kikklix Longlegs" },
    { "R.Hamgams", "Rutrix Hamgams" },
    { "S.Eaglebeak", "Snypestix Eaglebeak" },
    { "M.Wartpaws", "Mortilox Wartpaws" },
    { "J.Pigeonpecs", "Jabkix Pigeonpecs" },
    { "S.Thickhide", "Smeltix Thickhide" },
    { "W.Callusdigit", "Wasabix Callusdigit" },
    { "A.Sootwrists", "Anvilix Sootwrists" },
    { "B.Boneybod", "Blazox Boneybod" },
    { "B.Jaggedelbow", "Bootrix Jaggedelbow" },
    { "D.Stickytoes", "Distilix Stickytoes" },
    { "E.Snottynostril", "Eremix Snottynostrill" },
    { "J.Grannyguise", "Jabbrox Grannyguise" },
    { "M.Mucousmouth", "Mobpix Mucousmouth" },
    { "P.Barrelbelly", "Prowlox Barrelbelly" },
    { "S.Shaggychest", "Scruffix Shaggychest" },
    { "S.Megapeepers", "Slystix Megapeepers" },
    { "T.Ninefingers", "Tymexox Ninefingers" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_BEAUCEDINE] =
    {
        -- Normal Hydra Mobs
    { "H. Warrior", "Hydra Warrior" },
    { "H. Monk", "Hydra Monk" },
    { "H. White Mage", "Hydra White Mage" },
    { "H. Black Mage", "Hydra Black Mage" },
    { "H. Red Mage", "Hydra Red Mage" },
    { "H. Thief", "Hydra Thief" },
    { "H. Paladin", "Hydra Paladin" },
    { "H. Dark Knight", "Hydra Dark Knight" },
    { "H. Beastmaster", "Hydra Beastmaster" },
    { "H. Bard", "Hydra Bard" },
    { "H. Ranger", "Hydra Ranger" },
    { "H. Samurai", "Hydra Samurai" },
    { "H. Ninja", "Hydra Ninja" },
    { "H. Dragoon", "Hydra Dragoon" },
    { "H. Summoner", "Hydra Summoner" },
        -- Normal Quadav Mobs
    { "Adamantking Eff", "Adamantking Effigy" },
    { "Adamantking Img", "Adamantking Image" },
    { "Eff. Prototype", "Effigy Prototype" },
    { "V. Vindicator", "Vanguard Vindicator" },
    { "V. Militant", "Vanguard Militant" },
    { "V. Constable", "Vanguard Constable" },
    { "V. Thaumaturge", "Vanguard Thaumaturge" },
    { "V. Protector", "Vanguard Protector" },
    { "V. Purloiner", "Vanguard Purloiner" },
    { "V. Defender", "Vanguard Defender" },
    { "V. Vigilante", "Vanguard Vigilante" },
    { "V. Beasttender", "Vanguard Beasttender" },
    { "V. Minstrel", "Vanguard Minstrel" },
    { "V. Mason", "Vanguard Mason" },
    { "V. Hatamoto", "Vanguard Hatamoto" },
    { "V. Kusa", "Vanguard Kusa" },
    { "V. Drakekeeper", "Vanguard Drakekeeper" },
    { "V. Undertaker", "Vanguard Undertaker" },
        -- Normal Orc Mobs
    { "Serj. Tombstone", "Sergeant Tombstone" },
    { "War. Tombstone", "Warchief Tombstone" },
    { "Tomb. Prototype", "Tombstone Prototype" },
    { "V. Footsoldier", "Vanguard Footsoldier" },
    { "V. Grappler", "Vanguard Grappler" },
    { "V. Amputator", "Vanguard Amputator" },
    { "V. Mesmerizer", "Vanguard Mesmerizer" },
    { "V. Vexer", "Vanguard Vexer" },
    { "V. Pillager", "Vanguard Pillager" },
    { "V. Trooper", "Vanguard Trooper" },
    { "V. Neckchopper", "Vanguard Neckchopper" },
    { "V. Hawker", "Vanguard Hawker" },
    { "V. Bugler", "Vanguard Bugler" },
    { "V. Predator", "Vanguard Predator" },
    { "V. Gutslasher", "Vanguard Gutslaher" },
    { "V. Backstabber", "Vanguard Backstabber" },
    { "V. Impaler", "Vanguard Impaler" },
    { "V. Dollmaster", "Vanguard Dollmaster" },
        -- Normal Yagudo Mobs
    { "V. Skirmisher", "Vanguard Skirmisher" },
    { "V. Sentinel", "Vanguard Sentinel" },
    { "V. Priest", "Vanguard Priest" },
    { "V. Prelate", "Vanguard Prelate" },
    { "V. Visionary", "Vanguard Visionary" },
    { "V. Liberator", "Vanguard Liberator" },
    { "V. Exemplar", "Vanguard Exemplar" },
    { "V. Inciter", "Vanguard Inciter" },
    { "V. Ogresoother", "Vanguard Ogresoother" },
    { "V. Chanter", "Vanguard Chanter" },
    { "V. Salvager", "Vanguard Salvager" },
    { "V. Persecutor", "Vanguard Persecutor" },
    { "V. Assassin", "Vanguard Assassin" },
    { "V. Partisan", "Vanguard Partisan" },
    { "V. Oracle", "Vanguard Oracle" },
        -- Normal Goblin Mobs
    { "Stat. Prototype", "Statue Prototype" },
    { "V. Smithy", "Vanguard Smithy" },
    { "V. Pitfighter", "Vanguard Pitfighter" },
    { "V. Alchemist", "Vanguard Alchemist" },
    { "V. Shaman", "Vanguard Shaman" },
    { "V. Enchanter", "Vanguard Enchanter" },
    { "V. Welldigger", "Vanguard Welldigger" },
    { "V. Armorer", "Vanguard Armorer" },
    { "V. Tinkerer", "Vanguard Tinkerer" },
    { "V. Pathfinder", "Vanguard Pathfinder" },
    { "V. Maestro", "Vanguard Maestro" },
    { "V. Ambusher", "Vanguard Ambusher" },
    { "V. Ronin", "Vanguard Ronin" },
    { "V. Hitman", "Vanguard Hitman" },
    { "V. Dragontamer", "Vanguard Dragontamer" },
    { "V. Necromancer", "Vanguard Necromancer" },
        -- Beaucedine Specific Mobs
        -- Goblin NMs
    { "A.Ratgums", "Ascetox Ratgums" },
    { "B.Kittyback", "Bordox Kittyback" },
    { "B.Bittypupils", "Brewnix Bittypupils" },
    { "D.Scalecrust", "Draklix Scalecrust" },
    { "D.Granitepalms", "Droprix Granitepalms" },
    { "G.Pimplebeak", "Gibberox Pimplebeak" },
    { "M.Stubthunmbs", "Moltenox Stubthumbs" },
    { "M.Chubbychin", "Morblox Chubbychin" },
    { "R.Rubbertendon", "Routsix Rubbertendon" },
    { "R.Jumbolobes", "Ruffbix Jumbolobes" },
    { "S.Widebrow", "Shisox Widebrow" },
    { "S.Trufflesniff", "Slinkix Trufflesniff" },
    { "S.Tigershins", "Swypestix Tigershins" },
    { "T.Thinlids", "Tocktix Thinlids" },
    { "W.Toadthroat", "Whistix Toadthroat" },
        -- Orc NMs
    { "C.Buchzvotch", "Cobraclaw Buchzvotch" },
    { "D.Bidfbid", "Deathcaller Bidfbid" },
    { "D.Wubmfub", "Drakefeast Wubmfub" },
    { "E.Grokdok", "Elvaanlopper Grokdok" },
    { "G.Retzpratz", "Galkarider Retzpratz" },
    { "H.Djidzbad", "Heavymail Djidzbad" },
    { "H.Adzjbadj", "Humegutter Adzjbadj" },
    { "J.Gepkzip", "Jeunoraider Gepkzip" },
    { "L.Zapdjipp", "Lockbuster Zapdjipp" },
    { "M.Debhabob", "Mithraslaver Debhabob" },
    { "S.Ugghfogg", "Skinmask Ugghfogg" },
    { " S.Galflmall", "Spinalsucker Galflmall" },
    { "T.Biggsjig", "Taruroaster Biggsjig" },
    { "U.Zeknajak", "Ultrasonic Zeknajak" },
    { "W.Gidbnod", "Wraithdancer Gidbnod" },
        -- Quadav NMs
    { "B.Keeprazer", "Be'Zhe Keeprazer" },
    { "D.Pyrohand", "De'Bho Pyrohand" },
    { "G.Venomtouch", "Ga'Fho Venomtouch" },
    { "G.Magenapper", "Go'Tyo Magenapper" },
    { "G.Dukesniper", "Gu'Khu Dukesniper" },
    { "G.Wallstormer", "Gu'Nha Wallstormer" },
    { "J.Infiltrator", "Ji'Fhu Infiltrator" },
    { "J.Towercleaver", "Ji'Khu Towercleaver" },
    { "M.Whisperblade", "Mi'Rhe Whisperblade" },
    { "M.Legionkiller", "Mu'Gha Legionkiller" },
    { "N.Floodmaker", "Na'Hya Floodmaker" },
    { "N.Spiraleye", "Nu'Bhi Spiraleye" },
    { "S.Adderhandler", "So'Gho Adderhandler" },
    { "S.Metalbender", "So'Zho Metalbender" },
    { "T.Gallanthunter", "Ta'Hyu Gallanthunter" },
        -- Yagudo NMs
    { "B.Firepool", "Bhuu Wjato the Firepool" },
    { "C.Madpiercer", "Caa Xaza the Madpiercer" },
    { "F.Bloodcloak", "Foo Peku the Bloodcloak" },
    { "G.Preacher", "Guu Waji the Preacher" },
    { "H.Meticulous", "Hee Mida the Meticulous" },
    { "K.Bisector", "Knii Hoqo the Bisector" },
    { "K.Everfast", "Koo Saxu the Everfast" },
    { "K.Nimble", "Kuu Xuka the Nimble" },
    { "M.Wyrmkeeper", "Maa Zaua the Wyrmkeeper" },
    { "N.Judgemental", "Nee Huxa the Judgemental" },
    { "P.Phantasmal", "Puu Timu the Phantasmal" },
    { "R.Idolrobber", "Ryy Qihi the Idolrobber" },
    { "S.Fiendking", "Soo Jopo the Fiendking" },
    { "X.Roctalon", "Xaa Chau the Roctalon" },
    { "X.Sublime", "Xhoo Fuza the Sublime" },
    { "D. Statue", "Dynamis Statue" },
    { "D. Tombstone", "Dynamis Tombstone" },
    { "D. Effigy", "Dynamis Effigy" },
    { "D. Icon", "Dynamis Icon" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_XARCABARD] =
    {
        -- Statues
    { "Stat. Prototype", "Statue Prototype" },
    { "Tomb. Prototype", "Tombstone Prototype" },
    { "Eff. Prototype", "Effigy Prototype" },
        -- Normal Kindred Mobs
    { "K. Warrior", "Kindred Warrior" },
    { "K. Monk", "Kindred Monk" },
    { "K. White Mage", "Kindred White Mage" },
    { "K. Black Mage", "Kindred Black Mage" },
    { "K. Red Mage", "Kindred Red Mage" },
    { "K. Thief", "Kindred Thief" },
    { "K. Paladin", "Kindred Paladin" },
    { "K. Dark Knight", "Kindred Dark Knight" },
    { "K. Beastmaster", "Kindred Beastmaster" },
    { "K. Bard", "Kindred Bard" },
    { "K. Ranger", "Kindred Ranger" },
    { "K. Samurai", "Kindred Samurai" },
    { "K. Ninja", "Kindred Ninja" },
    { "K. Dragoon", "Kindred Dragoon" },
    { "K. Summoner", "Kindred Summoner" },
        -- Animated / Satellite Weapons
    { "A.Hammer", "Animated Hammer" },
    { "A.Staff", "Animated Staff" },
    { "A.Longsword", "Animated Longsword" },
    { "A.Tabar", "Animated Tabar" },
    { "A.Great Axe", "Animated Great Axe" },
    { "A.Claymore", "Animated Claymore" },
    { "A.Spear", "Animated Spear" },
    { "A.Scythe", "Animated Scythe" },
    { "A.Kunai", "Animated Kunai" },
    { "A.Tachi", "Animated Tachi" },
    { "A.Dagger", "Animated Dagger" },
    { "A.Knuckles", "Animated Knuckles" },
    { "A.Longbow", "Animated Longbow" },
    { "A.Gun", "Animated Gun" },
    { "A.Horn", "Animated Horn" },
    { "A.Shield", "Animated Shield" },
    { "S.Hammer", "Satellite Hammer" },
    { "S.Staff", "Satellite Staff" },
    { "S.Longsword", "Satellite Longsword" },
    { "S.Tabar", "Satellite Tabar" },
    { "S.Great Axe", "Satellite Great Axe" },
    { "S.Claymore", "Satellite Claymore" },
    { "S.Spear", "Satellite Spear" },
    { "S.Scythe", "Satellite Scythe" },
    { "S.Kunai", "Satellite Kunai" },
    { "S.Tachi", "Satellite Tachi" },
    { "S.Dagger", "Satellite Dagger" },
    { "S.Knuckles", "Satellite Knuckles" },
    { "S.Longbow", "Satellite Longbow" },
    { "S.Gun", "Satellite Gun" },
    { "S.Horn", "Satellite Horn" },
    { "S.Shield", "Satellite Shield" },
        -- Xarcabard Specific Mobs
    { "V. Dragon", "Vanguard Dragon" },
    { "C.Zaebos", "Count Zaebos" },
    { "D.Berith", "Duke Berith" },
    { "M.Decarabia", "Marquis Decarabia" },
    { "D.Gomory", "Duke Gomory" },
    { "M.Andras", "Marquis Andras" },
    { "P.Seere", "Prince Seere" },
    { "D.Scox", "Duke Scox" },
    { "M.Gamygyn", "Marquis Gamygyn" },
    { "M.Orias", "Marquis Orias" },
    { "C.Raum", "Count Raum" },
    { "M.Nebiros", "Marquis Nebiros" },
    { "M.Sabnak", "Marquis Sabnak" },
    { "C.Vine", "Count Vine" },
    { "K.Zagan", "King Zagan" },
    { "M.Cimeries", "Marquis Cimeries" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_BUBURIMU] =
    {
        -- Normal Quadav Mobs
    { "Adamantking Eff", "Adamantking Effigy" },
    { "Adamantking Img", "Adamantking Image" },
    { "Eff. Prototype", "Effigy Prototype" },
    { "V. Vindicator", "Vanguard Vindicator" },
    { "V. Militant", "Vanguard Militant" },
    { "V. Constable", "Vanguard Constable" },
    { "V. Thaumaturge", "Vanguard Thaumaturge" },
    { "V. Protector", "Vanguard Protector" },
    { "V. Purloiner", "Vanguard Purloiner" },
    { "V. Defender", "Vanguard Defender" },
    { "V. Vigilante", "Vanguard Vigilante" },
    { "V. Beasttender", "Vanguard Beasttender" },
    { "V. Minstrel", "Vanguard Minstrel" },
    { "V. Mason", "Vanguard Mason" },
    { "V. Hatamoto", "Vanguard Hatamoto" },
    { "V. Kusa", "Vanguard Kusa" },
    { "V. Drakekeeper", "Vanguard Drakekeeper" },
    { "V. Undertaker", "Vanguard Undertaker" },
        -- Normal Orc Mobs
    { "Serj. Tombstone", "Sergeant Tombstone" },
    { "War. Tombstone", "Warchief Tombstone" },
    { "Tomb. Prototype", "Tombstone Prototype" },
    { "V. Footsoldier", "Vanguard Footsoldier" },
    { "V. Grappler", "Vanguard Grappler" },
    { "V. Amputator", "Vanguard Amputator" },
    { "V. Mesmerizer", "Vanguard Mesmerizer" },
    { "V. Vexer", "Vanguard Vexer" },
    { "V. Pillager", "Vanguard Pillager" },
    { "V. Trooper", "Vanguard Trooper" },
    { "V. Neckchopper", "Vanguard Neckchopper" },
    { "V. Hawker", "Vanguard Hawker" },
    { "V. Bugler", "Vanguard Bugler" },
    { "V. Predator", "Vanguard Predator" },
    { "V. Gutslasher", "Vanguard Gutslaher" },
    { "V. Backstabber", "Vanguard Backstabber" },
    { "V. Impaler", "Vanguard Impaler" },
    { "V. Dollmaster", "Vanguard Dollmaster" },
        -- Normal Yagudo Mobs
    { "V. Skirmisher", "Vanguard Skirmisher" },
    { "V. Sentinel", "Vanguard Sentinel" },
    { "V. Priest", "Vanguard Priest" },
    { "V. Prelate", "Vanguard Prelate" },
    { "V. Visionary", "Vanguard Visionary" },
    { "V. Liberator", "Vanguard Liberator" },
    { "V. Exemplar", "Vanguard Exemplar" },
    { "V. Inciter", "Vanguard Inciter" },
    { "V. Ogresoother", "Vanguard Ogresoother" },
    { "V. Chanter", "Vanguard Chanter" },
    { "V. Salvager", "Vanguard Salvager" },
    { "V. Persecutor", "Vanguard Persecutor" },
    { "V. Assassin", "Vanguard Assassin" },
    { "V. Partisan", "Vanguard Partisan" },
    { "V. Oracle", "Vanguard Oracle" },
        -- Normal Goblin Mobs
    { "Stat. Prototype", "Statue Prototype" },
    { "V. Smithy", "Vanguard Smithy" },
    { "V. Pitfighter", "Vanguard Pitfighter" },
    { "V. Alchemist", "Vanguard Alchemist" },
    { "V. Shaman", "Vanguard Shaman" },
    { "V. Enchanter", "Vanguard Enchanter" },
    { "V. Welldigger", "Vanguard Welldigger" },
    { "V. Armorer", "Vanguard Armorer" },
    { "V. Tinkerer", "Vanguard Tinkerer" },
    { "V. Pathfinder", "Vanguard Pathfinder" },
    { "V. Maestro", "Vanguard Maestro" },
    { "V. Ambusher", "Vanguard Ambusher" },
    { "V. Ronin", "Vanguard Ronin" },
    { "V. Hitman", "Vanguard Hitman" },
    { "V. Dragontamer", "Vanguard Dragontamer" },
    { "V. Necromancer", "Vanguard Necromancer" },
        -- Nightmare Mobs
    { "N. Bunny", "Nightmare Bunny" },
    { "N. Eft", "Nightmare Eft" },
    { "N. Mandragor", "Nightmare Mandragora" },
    { "N. Crawler", "Nightmare Crawler" },
    { "N. Raven", "Nightmare Raven" },
    { "N. Urganite", "Nightmare Urganite" },
    { "N. Crab", "Nightmare Crab" },
    { "N. Dhalmel", "Nightmare Dhalmel" },
    { "N. Scorpion", "Nightmare Scorpion" },
    { "N. Cockatrice", "Nightmare Cockatrice" },
        -- Buburimu Specific Mobs
    { "G.Blabberlips", "Gosspix Blabberlips" },
    { "S.Rottenheart", "Shamblix Rottenheart" },
    { "W.Shrillwhistle", "Woodnix Shrillwhistle" },
    { "E.Bxafraff", "Elvaansticker Bxafraff" },
    { "F.Zoeqdoq, ", "Flamecaller Zoeqdoq" },
    { "H.Gukhbuk", "Hamfist Gukhbuk" },
    { "L.Juvgneg", "Lyncean Juvgneg" },
    { "G.Flesheater", "Gi'Bhe Flesheater" },
    { "Q.Bloodspiller", "Qu'Pho Bloodspiller" },
    { "T.Ironclad", "Te'Zha Ironclad" },
    { "V.Bodysnatcher", "Va'Rhu Bodysnatcher" },
    { "B.Bibliopage", "Baa Dava the Bibliopage" },
    { "D.Fleetfoot", "Doo Peku the Fleetfoot" },
    { "K.Levinblade", "Koo Rahi the Levinblade" },
    { "R.Melomanic", "Ree Nata the Melomanic" },
    { "Apoc. Beast", "Apocalyptic Beast" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_QUFIM] =
    {
        -- Normal Quadav Mobs
    { "Adamantking Eff", "Adamantking Effigy" },
    { "Adamantking Img", "Adamantking Image" },
    { "Eff. Prototype", "Effigy Prototype" },
    { "V. Vindicator", "Vanguard Vindicator" },
    { "V. Militant", "Vanguard Militant" },
    { "V. Constable", "Vanguard Constable" },
    { "V. Thaumaturge", "Vanguard Thaumaturge" },
    { "V. Protector", "Vanguard Protector" },
    { "V. Purloiner", "Vanguard Purloiner" },
    { "V. Defender", "Vanguard Defender" },
    { "V. Vigilante", "Vanguard Vigilante" },
    { "V. Beasttender", "Vanguard Beasttender" },
    { "V. Minstrel", "Vanguard Minstrel" },
    { "V. Mason", "Vanguard Mason" },
    { "V. Hatamoto", "Vanguard Hatamoto" },
    { "V. Kusa", "Vanguard Kusa" },
    { "V. Drakekeeper", "Vanguard Drakekeeper" },
    { "V. Undertaker", "Vanguard Undertaker" },
        -- Normal Orc Mobs
    { "Serj. Tombstone", "Sergeant Tombstone" },
    { "War. Tombstone", "Warchief Tombstone" },
    { "Tomb. Prototype", "Tombstone Prototype" },
    { "V. Footsoldier", "Vanguard Footsoldier" },
    { "V. Grappler", "Vanguard Grappler" },
    { "V. Amputator", "Vanguard Amputator" },
    { "V. Mesmerizer", "Vanguard Mesmerizer" },
    { "V. Vexer", "Vanguard Vexer" },
    { "V. Pillager", "Vanguard Pillager" },
    { "V. Trooper", "Vanguard Trooper" },
    { "V. Neckchopper", "Vanguard Neckchopper" },
    { "V. Hawker", "Vanguard Hawker" },
    { "V. Bugler", "Vanguard Bugler" },
    { "V. Predator", "Vanguard Predator" },
    { "V. Gutslasher", "Vanguard Gutslaher" },
    { "V. Backstabber", "Vanguard Backstabber" },
    { "V. Impaler", "Vanguard Impaler" },
    { "V. Dollmaster", "Vanguard Dollmaster" },
        -- Normal Yagudo Mobs
    { "V. Skirmisher", "Vanguard Skirmisher" },
    { "V. Sentinel", "Vanguard Sentinel" },
    { "V. Priest", "Vanguard Priest" },
    { "V. Prelate", "Vanguard Prelate" },
    { "V. Visionary", "Vanguard Visionary" },
    { "V. Liberator", "Vanguard Liberator" },
    { "V. Exemplar", "Vanguard Exemplar" },
    { "V. Inciter", "Vanguard Inciter" },
    { "V. Ogresoother", "Vanguard Ogresoother" },
    { "V. Chanter", "Vanguard Chanter" },
    { "V. Salvager", "Vanguard Salvager" },
    { "V. Persecutor", "Vanguard Persecutor" },
    { "V. Assassin", "Vanguard Assassin" },
    { "V. Partisan", "Vanguard Partisan" },
    { "V. Oracle", "Vanguard Oracle" },
        -- Normal Goblin Mobs
    { "Stat. Prototype", "Statue Prototype" },
    { "V. Smithy", "Vanguard Smithy" },
    { "V. Pitfighter", "Vanguard Pitfighter" },
    { "V. Alchemist", "Vanguard Alchemist" },
    { "V. Shaman", "Vanguard Shaman" },
    { "V. Enchanter", "Vanguard Enchanter" },
    { "V. Welldigger", "Vanguard Welldigger" },
    { "V. Armorer", "Vanguard Armorer" },
    { "V. Tinkerer", "Vanguard Tinkerer" },
    { "V. Pathfinder", "Vanguard Pathfinder" },
    { "V. Maestro", "Vanguard Maestro" },
    { "V. Ambusher", "Vanguard Ambusher" },
    { "V. Ronin", "Vanguard Ronin" },
    { "V. Hitman", "Vanguard Hitman" },
    { "V. Dragontamer", "Vanguard Dragontamer" },
    { "V. Necromancer", "Vanguard Necromancer" },
        -- Nightmare Mobs
    { "N. Snoll", "Nightmare Snoll" },
    { "N. Stirge", "Nightmare Stirge" },
    { "N. Weapon", "Nightmare Weapon" },
    { "N. Gaylas", "Nightmare Gaylas" },
    { "N. Kraken", "Nightmare Kraken" },
    { "N. Roc", "Nightmare Roc" },
    { "N. Diremite", "Nightmare Diremite" },
    { "N. Raptor", "Nightmare Raptor" },
    { "N. Tiger", "Nightmare Tiger" },
        -- Elementals
    { "Fire Ele.", "Fire Elemental" },
    { "Water Ele.", "Water Elemental" },
    { "Thunder Ele.", "Thunder Elemental" },
    { "Earth Ele.", "Earth Elemental" },
    { "Air Ele.", "Air Elemental" },
    { "Ice Ele.", "Ice Elemental" },
    { "Light Ele.", "Light Elemental" },
    { "Dark Ele.", "Dark Elemental" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },

    [xi.zone.DYNAMIS_VALKURM] =
    {
        -- Normal Quadav Mobs
    { "Adamantking Eff", "Adamantking Effigy" },
    { "Adamantking Img", "Adamantking Image" },
    { "Eff. Prototype", "Effigy Prototype" },
    { "V. Vindicator", "Vanguard Vindicator" },
    { "V. Militant", "Vanguard Militant" },
    { "V. Constable", "Vanguard Constable" },
    { "V. Thaumaturge", "Vanguard Thaumaturge" },
    { "V. Protector", "Vanguard Protector" },
    { "V. Purloiner", "Vanguard Purloiner" },
    { "V. Defender", "Vanguard Defender" },
    { "V. Vigilante", "Vanguard Vigilante" },
    { "V. Beasttender", "Vanguard Beasttender" },
    { "V. Minstrel", "Vanguard Minstrel" },
    { "V. Mason", "Vanguard Mason" },
    { "V. Hatamoto", "Vanguard Hatamoto" },
    { "V. Kusa", "Vanguard Kusa" },
    { "V. Drakekeeper", "Vanguard Drakekeeper" },
    { "V. Undertaker", "Vanguard Undertaker" },
        -- Normal Orc Mobs
    { "Serj. Tombstone", "Sergeant Tombstone" },
    { "War. Tombstone", "Warchief Tombstone" },
    { "Tomb. Prototype", "Tombstone Prototype" },
    { "V. Footsoldier", "Vanguard Footsoldier" },
    { "V. Grappler", "Vanguard Grappler" },
    { "V. Amputator", "Vanguard Amputator" },
    { "V. Mesmerizer", "Vanguard Mesmerizer" },
    { "V. Vexer", "Vanguard Vexer" },
    { "V. Pillager", "Vanguard Pillager" },
    { "V. Trooper", "Vanguard Trooper" },
    { "V. Neckchopper", "Vanguard Neckchopper" },
    { "V. Hawker", "Vanguard Hawker" },
    { "V. Bugler", "Vanguard Bugler" },
    { "V. Predator", "Vanguard Predator" },
    { "V. Gutslasher", "Vanguard Gutslaher" },
    { "V. Backstabber", "Vanguard Backstabber" },
    { "V. Impaler", "Vanguard Impaler" },
    { "V. Dollmaster", "Vanguard Dollmaster" },
        -- Normal Yagudo Mobs
    { "V. Skirmisher", "Vanguard Skirmisher" },
    { "V. Sentinel", "Vanguard Sentinel" },
    { "V. Priest", "Vanguard Priest" },
    { "V. Prelate", "Vanguard Prelate" },
    { "V. Visionary", "Vanguard Visionary" },
    { "V. Liberator", "Vanguard Liberator" },
    { "V. Exemplar", "Vanguard Exemplar" },
    { "V. Inciter", "Vanguard Inciter" },
    { "V. Ogresoother", "Vanguard Ogresoother" },
    { "V. Chanter", "Vanguard Chanter" },
    { "V. Salvager", "Vanguard Salvager" },
    { "V. Persecutor", "Vanguard Persecutor" },
    { "V. Assassin", "Vanguard Assassin" },
    { "V. Partisan", "Vanguard Partisan" },
    { "V. Oracle", "Vanguard Oracle" },
        -- Normal Goblin Mobs
    { "Stat. Prototype", "Statue Prototype" },
    { "V. Smithy", "Vanguard Smithy" },
    { "V. Pitfighter", "Vanguard Pitfighter" },
    { "V. Alchemist", "Vanguard Alchemist" },
    { "V. Shaman", "Vanguard Shaman" },
    { "V. Enchanter", "Vanguard Enchanter" },
    { "V. Welldigger", "Vanguard Welldigger" },
    { "V. Armorer", "Vanguard Armorer" },
    { "V. Tinkerer", "Vanguard Tinkerer" },
    { "V. Pathfinder", "Vanguard Pathfinder" },
    { "V. Maestro", "Vanguard Maestro" },
    { "V. Ambusher", "Vanguard Ambusher" },
    { "V. Ronin", "Vanguard Ronin" },
    { "V. Hitman", "Vanguard Hitman" },
    { "V. Dragontamer", "Vanguard Dragontamer" },
    { "V. Necromancer", "Vanguard Necromancer" },
        -- Nightmare Mobs
    { "N. Hippogryph", "Nightmare Hippogryph" },
    { "N. Sabotender", "Nightmare Sabotender" },
    { "N. Sheep", "Nightmare Sheep" },
    { "N. Fly", "Nightmare Fly" },
    { "N. Manticore", "Nightmare Manticore" },
        -- Valkurm Specific Mobs
    { "N. Morbol", "Nightmare Morbol" },
    { "C. Christelle", "Cirrate Christelle" },
        -- Pets
    { "V. Slime", "Vanguard's Slime" },
    { "W. Slime", "Woodnix's Slime" },
    { "V. Scorpion", "Vanguard's Scorpion" },
    { "V. Crow", "Vanguard's Crow" },
    { "V. Hecteyes", "Vanguard's Hecteyes" },
    { "H. Hound", "Hydra's Hound" },
    { "D. Hound", "Dagourmarche's Hound" },
    { "K. Vouvire", "Kindred's Vouvire" },
    { "A. Vouvire", "Andras' Vouvire" },
    { "V. Wyvern", "Vanguard's Wyvern" },
    { "K. Wyvern", "Kindred's Wyvern" },
    { "H. Wyvern", "Hydra's Wyvern" },
    { "D. Wyvern", "Dagourmarche's Wyvern" },
    { "V. Avatar", "Vanguard's Avatar" },
    { "K. Avatar", "Kindred's Avatar" },
    { "H. Avatar", "Hydra's Avatar" },
    { "D. Avatar", "Dagourmarche's Avatar" },
    },
    [xi.zone.CRAWLERS_NEST] =
    {
        { "Soldier Crawler", "King Crawler" },
        { "Hornly", "Dancing Jewel" },
    },
    [xi.zone.DEN_OF_RANCOR] =
    {
        { "Stygian Pugil", "Demonic Pugil" },
    },
}
return list
