local ID = zones[xi.zone.LOWER_JEUNO]

return {
    ['_6t2']            = { event = 64 },
    ['Amhu_Sabaroleka'] = { event = 14 },
    ['Biora']           = { event = 205 },
    ['Bluffnix']        = { event = 43, options = 81 },
    ['Bogharg']         = { event = 45 },
    ['Chimh_Dlesbah']   = { event = 10096 },
    ['Crazy_Wolf']      = { event = 165 },
    ['Danzhor']         = { event = 185 },
    ['Faursel']         = { event = 10065 },
    ['Garnev']          = { event = 207 },
    ['Geuhbe']          = { event = 10033 },
    ['Ghebi_Damomohe']  = { event = 106, 4 },
    ['Guide_Stone']     = { messageSpecial = ID.text.GUIDE_STONE },
    ['Gurdern']         = { event = 112 },
    ['Harnek']          = { event = 217 },
    ['Honorine']        = { event = 10015 },
    ['Jazmin']          = { event = 226 },
    ['Joseph']          = { event = 133 },
    ['Kikilolo']        = { event = 222 },
    ['Kuah_Dakonsa']    = { event = 190 },
    ['Liki_Steligho']   = { event = 10097 },
    ['Miladi-Nildi']    = { event = 97 },
    ['Momiji']          = { event = 223 },
    ['Muckvix']         = { event = 15 },
    ['Nakho_Jawantal']  = { event = 41 },
    ['Navisse']         = { event = 153 },
    ['Odasel']          = { event = 162 },
    ['Omer']            = { event = 206 },
    ['Parike-Poranke']  = { messageSpecial = ID.text.PARIKE_PORANKE_DIALOG },
    ['Raji']            = { event = 195 },
    ['Saprut']          = { event = 224 },
    ['Sattal-Mansal']   = { event = 96 },
    ['Seyaya']          = { event = 18 },
    ['Shomera']         = { event = 195 },
    ['Sutarara']        = { event = 208 },
    ['Tawfeeq']         = { event = 225 },
    ['Taza']            = { text = ID.text.WAAG_DEEG_SHOP_DIALOG },
    ['Teigero-Bangero'] = { event = 34 },
    ['Tovrutaux']       = { event = 58 },
    ['Venika']          = { event = 110 },
    ['Yamilla']         = { event = 109 },
    ['Yatniel']         = { event = 10028 },
}
