-- ---------------------------------------------------------------------------
--  Notes: Updates zone_settings with the proper port for clusters.
-- ---------------------------------------------------------------------------

SET @Abdhaljs = 54306;
SET @AhtUrhgan = 54245;
SET @Alzadaal = 54266;
SET @Aragoneu = 54251;
SET @Arrapago = 54236;
SET @Bastok = 54298;
SET @Bazaar_and_Jail = 54247;
SET @Derfland = 54248;
SET @Disabled = 0;
SET @Elshimo = 54252;
SET @Fauregandi = 54253;
SET @Gustaberg = 54254;
SET @Halvung = 54249;
SET @Jeuno = 54232;
SET @Kolshushu = 54234;
SET @Kuzotz = 54255;
SET @Li_Telor = 54256;
SET @Lumoria = 54305;
SET @Mamool = 54250;
SET @Movalpolos_Norvallen = 54257;
SET @Other = 54345;
SET @Past = 54233;
SET @Past_South = 54309;
SET @Past_East = 54308;
SET @Promy = 54270;
SET @Qufim = 54258;
SET @Ronfaure = 54259;
SET @Sandoria = 54300;
SET @Sarutabaruta = 54260;
SET @Tavnazia = 54268;
SET @Tu_Lia = 54267;
SET @Valdeaunia = 54261;
SET @Vollbow = 54262;
SET @Windurst = 54297;
SET @Zulkheim = 54235;

UPDATE zone_settings SET zoneport=@Other WHERE name='unknown';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Phanauet_Channel';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Carpenters_Landing';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Manaclipper';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Bibiki_Bay';
UPDATE zone_settings SET zoneport=@Valdeaunia WHERE name='Uleguerand_Range';
UPDATE zone_settings SET zoneport=@Valdeaunia WHERE name='Bearclaw_Pinnacle';
UPDATE zone_settings SET zoneport=@Aragoneu WHERE name='Attohwa_Chasm';
UPDATE zone_settings SET zoneport=@Aragoneu WHERE name='Boneyard_Gully';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='PsoXja';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='The_Shrouded_Maw';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Oldton_Movalpolos';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Newton_Movalpolos';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Mine_Shaft_2716';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Hall_of_Transference';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Konschtat';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Promyvion-Holla';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Spire_of_Holla';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Promyvion-Dem';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Spire_of_Dem';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Promyvion-Mea';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Spire_of_Mea';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Promyvion-Vahzl';
UPDATE zone_settings SET zoneport=@Promy WHERE name='Spire_of_Vahzl';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Lufaise_Meadows';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Misareaux_Coast';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Tavnazian_Safehold';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Phomiuna_Aqueducts';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Sacrarium';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Riverne-Site_B01';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Riverne-Site_A01';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Monarch_Linn';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Sealions_Den';
UPDATE zone_settings SET zoneport=@Lumoria WHERE name='AlTaieu';
UPDATE zone_settings SET zoneport=@Lumoria WHERE name='Grand_Palace_of_HuXzoi';
UPDATE zone_settings SET zoneport=@Lumoria WHERE name='The_Garden_of_RuHmet';
UPDATE zone_settings SET zoneport=@Lumoria WHERE name='Empyreal_Paradox';
UPDATE zone_settings SET zoneport=@Lumoria WHERE name='Temenos';
UPDATE zone_settings SET zoneport=@Lumoria WHERE name='Apollyon';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Dynamis-Valkurm';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Dynamis-Buburimu';
UPDATE zone_settings SET zoneport=@Qufim WHERE name='Dynamis-Qufim';
UPDATE zone_settings SET zoneport=@Tavnazia WHERE name='Dynamis-Tavnazia';
UPDATE zone_settings SET zoneport=@Abdhaljs WHERE name='Diorama_Abdhaljs-Ghelsba';
UPDATE zone_settings SET zoneport=@Abdhaljs WHERE name='Abdhaljs_Isle-Purgonorgo';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Tahrongi';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Open_sea_route_to_Al_Zahbi';
UPDATE zone_settings SET zoneport=@AhtUrhgan WHERE name='Open_sea_route_to_Mhaura';
UPDATE zone_settings SET zoneport=@AhtUrhgan WHERE name='Al_Zahbi';
UPDATE zone_settings SET zoneport=@Other WHERE name='49';
UPDATE zone_settings SET zoneport=@AhtUrhgan WHERE name='Aht_Urhgan_Whitegate';
UPDATE zone_settings SET zoneport=@Mamool WHERE name='Wajaom_Woodlands';
UPDATE zone_settings SET zoneport=@Mamool WHERE name='Bhaflau_Thickets';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Nashmau';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Arrapago_Reef';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Ilrusi_Atoll';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Periqia';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Talacca_Cove';
UPDATE zone_settings SET zoneport=@AhtUrhgan WHERE name='Silver_Sea_route_to_Nashmau';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Silver_Sea_route_to_Al_Zahbi';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='The_Ashu_Talif';
UPDATE zone_settings SET zoneport=@Halvung WHERE name='Mount_Zhayolm';
UPDATE zone_settings SET zoneport=@Halvung WHERE name='Halvung';
UPDATE zone_settings SET zoneport=@Halvung WHERE name='Lebros_Cavern';
UPDATE zone_settings SET zoneport=@Halvung WHERE name='Navukgo_Execution_Chamber';
UPDATE zone_settings SET zoneport=@Mamool WHERE name='Mamook';
UPDATE zone_settings SET zoneport=@Mamool WHERE name='Mamool_Ja_Training_Grounds';
UPDATE zone_settings SET zoneport=@Mamool WHERE name='Jade_Sepulcher';
UPDATE zone_settings SET zoneport=@Mamool WHERE name='Aydeewa_Subterrane';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Leujaoam_Sanctum';
UPDATE zone_settings SET zoneport=@Other WHERE name='Chocobo_Circuit';
UPDATE zone_settings SET zoneport=@AhtUrhgan WHERE name='The_Colosseum';
UPDATE zone_settings SET zoneport=@Alzadaal WHERE name='Alzadaal_Undersea_Ruins';
UPDATE zone_settings SET zoneport=@Alzadaal WHERE name='Zhayolm_Remnants';
UPDATE zone_settings SET zoneport=@Alzadaal WHERE name='Arrapago_Remnants';
UPDATE zone_settings SET zoneport=@Alzadaal WHERE name='Bhaflau_Remnants';
UPDATE zone_settings SET zoneport=@Alzadaal WHERE name='Silver_Sea_Remnants';
UPDATE zone_settings SET zoneport=@Alzadaal WHERE name='Nyzul_Isle';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Hazhalm_Testing_Grounds';
UPDATE zone_settings SET zoneport=@Arrapago WHERE name='Caedarva_Mire';
UPDATE zone_settings SET zoneport=@Past WHERE name='Southern_San_dOria_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='East_Ronfaure_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Jugner_Forest_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Vunkerl_Inlet_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Batallia_Downs_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='La_Vaule_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Everbloom_Hollow';
UPDATE zone_settings SET zoneport=@Past_South WHERE name='Bastok_Markets_[S]';
UPDATE zone_settings SET zoneport=@Past_South WHERE name='North_Gustaberg_[S]';
UPDATE zone_settings SET zoneport=@Past_South WHERE name='Grauberg_[S]';
UPDATE zone_settings SET zoneport=@Past_South WHERE name='Pashhow_Marshlands_[S]';
UPDATE zone_settings SET zoneport=@Past_South WHERE name='Rolanberry_Fields_[S]';
UPDATE zone_settings SET zoneport=@Past_South WHERE name='Beadeaux_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Ruhotz_Silvermines';
UPDATE zone_settings SET zoneport=@Past_East WHERE name='Windurst_Waters_[S]';
UPDATE zone_settings SET zoneport=@Past_East WHERE name='West_Sarutabaruta_[S]';
UPDATE zone_settings SET zoneport=@Past_East WHERE name='Fort_Karugo-Narugo_[S]';
UPDATE zone_settings SET zoneport=@Past_East WHERE name='Meriphataud_Mountains_[S]';
UPDATE zone_settings SET zoneport=@Past_East WHERE name='Sauromugue_Champaign_[S]';
UPDATE zone_settings SET zoneport=@Past_East WHERE name='Castle_Oztroja_[S]';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='West_Ronfaure';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='East_Ronfaure';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='La_Theine_Plateau';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Valkurm_Dunes';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Jugner_Forest';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Batallia_Downs';
UPDATE zone_settings SET zoneport=@Gustaberg WHERE name='North_Gustaberg';
UPDATE zone_settings SET zoneport=@Gustaberg WHERE name='South_Gustaberg';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Konschtat_Highlands';
UPDATE zone_settings SET zoneport=@Derfland WHERE name='Pashhow_Marshlands';
UPDATE zone_settings SET zoneport=@Derfland WHERE name='Rolanberry_Fields';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='Beaucedine_Glacier';
UPDATE zone_settings SET zoneport=@Valdeaunia WHERE name='Xarcabard';
UPDATE zone_settings SET zoneport=@Vollbow WHERE name='Cape_Teriggan';
UPDATE zone_settings SET zoneport=@Kuzotz WHERE name='Eastern_Altepa_Desert';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='West_Sarutabaruta';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='East_Sarutabaruta';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Tahrongi_Canyon';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Buburimu_Peninsula';
UPDATE zone_settings SET zoneport=@Aragoneu WHERE name='Meriphataud_Mountains';
UPDATE zone_settings SET zoneport=@Aragoneu WHERE name='Sauromugue_Champaign';
UPDATE zone_settings SET zoneport=@Li_Telor WHERE name='The_Sanctuary_of_ZiTah';
UPDATE zone_settings SET zoneport=@Li_Telor WHERE name='RoMaeve';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Yuhtunga_Jungle';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Yhoator_Jungle';
UPDATE zone_settings SET zoneport=@Kuzotz WHERE name='Western_Altepa_Desert';
UPDATE zone_settings SET zoneport=@Qufim WHERE name='Qufim_Island';
UPDATE zone_settings SET zoneport=@Qufim WHERE name='Behemoths_Dominion';
UPDATE zone_settings SET zoneport=@Vollbow WHERE name='Valley_of_Sorrows';
UPDATE zone_settings SET zoneport=@Past WHERE name='Ghoyus_Reverie';
UPDATE zone_settings SET zoneport=@Tu_Lia WHERE name='RuAun_Gardens';
UPDATE zone_settings SET zoneport=@Bazaar_and_Jail WHERE name='Mordion_Gaol';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-La_Theine';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='133';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='Dynamis-Beaucedine';
UPDATE zone_settings SET zoneport=@Valdeaunia WHERE name='Dynamis-Xarcabard';
UPDATE zone_settings SET zoneport=@Past WHERE name='Beaucedine_Glacier_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Xarcabard_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Castle_Zvahl_Baileys_[S]';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='Horlais_Peak';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='Ghelsba_Outpost';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='Fort_Ghelsba';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='Yughott_Grotto';
UPDATE zone_settings SET zoneport=@Gustaberg WHERE name='Palborough_Mines';
UPDATE zone_settings SET zoneport=@Gustaberg WHERE name='Waughroon_Shrine';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='Giddeus';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='Balgas_Dais';
UPDATE zone_settings SET zoneport=@Derfland WHERE name='Beadeaux';
UPDATE zone_settings SET zoneport=@Derfland WHERE name='Qulun_Dome';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Davoi';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='Monastic_Cavern';
UPDATE zone_settings SET zoneport=@Aragoneu WHERE name='Castle_Oztroja';
UPDATE zone_settings SET zoneport=@Aragoneu WHERE name='Altar_Room';
UPDATE zone_settings SET zoneport=@Li_Telor WHERE name='The_Boyahda_Tree';
UPDATE zone_settings SET zoneport=@Li_Telor WHERE name='Dragons_Aery';
UPDATE zone_settings SET zoneport=@Past WHERE name='Castle_Zvahl_Keep_[S]';
UPDATE zone_settings SET zoneport=@Past WHERE name='Throne_Room_[S]';
UPDATE zone_settings SET zoneport=@Qufim WHERE name='Middle_Delkfutts_Tower';
UPDATE zone_settings SET zoneport=@Qufim WHERE name='Upper_Delkfutts_Tower';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Temple_of_Uggalepih';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Den_of_Rancor';
UPDATE zone_settings SET zoneport=@Valdeaunia WHERE name='Castle_Zvahl_Baileys';
UPDATE zone_settings SET zoneport=@Valdeaunia WHERE name='Castle_Zvahl_Keep';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Sacrificial_Chamber';
UPDATE zone_settings SET zoneport=@Past_East WHERE name='Garlaige_Citadel_[S]';
UPDATE zone_settings SET zoneport=@Valdeaunia WHERE name='Throne_Room';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='Ranguemont_Pass';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='Bostaunieux_Oubliette';
UPDATE zone_settings SET zoneport=@Kuzotz WHERE name='Chamber_of_Oracles';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='Toraimarai_Canal';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='Full_Moon_Fountain';
UPDATE zone_settings SET zoneport=@Past_South WHERE name='Crawlers_Nest_[S]';
UPDATE zone_settings SET zoneport=@Gustaberg WHERE name='Zeruhn_Mines';
UPDATE zone_settings SET zoneport=@Gustaberg WHERE name='Korroloka_Tunnel';
UPDATE zone_settings SET zoneport=@Vollbow WHERE name='Kuftal_Tunnel';
UPDATE zone_settings SET zoneport=@Past WHERE name='The_Eldieme_Necropolis_[S]';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Sea_Serpent_Grotto';
UPDATE zone_settings SET zoneport=@Tu_Lia WHERE name='VeLugannon_Palace';
UPDATE zone_settings SET zoneport=@Tu_Lia WHERE name='The_Shrine_of_RuAvitau';
UPDATE zone_settings SET zoneport=@Qufim WHERE name='Stellar_Fulcrum';
UPDATE zone_settings SET zoneport=@Tu_Lia WHERE name='LaLoff_Amphitheater';
UPDATE zone_settings SET zoneport=@Tu_Lia WHERE name='The_Celestial_Nexus';
UPDATE zone_settings SET zoneport=@Past WHERE name='Walk_of_Echoes';
UPDATE zone_settings SET zoneport=@Abdhaljs WHERE name='Maquette_Abdhaljs-Legion_A';
UPDATE zone_settings SET zoneport=@Qufim WHERE name='Lower_Delkfutts_Tower';
UPDATE zone_settings SET zoneport=@Sandoria WHERE name='Dynamis-San_dOria';
UPDATE zone_settings SET zoneport=@Bastok WHERE name='Dynamis-Bastok';
UPDATE zone_settings SET zoneport=@Windurst WHERE name='Dynamis-Windurst';
UPDATE zone_settings SET zoneport=@Jeuno WHERE name='Dynamis-Jeuno';
UPDATE zone_settings SET zoneport=@Other WHERE name='Residential_Area';
UPDATE zone_settings SET zoneport=@Ronfaure WHERE name='King_Ranperres_Tomb';
UPDATE zone_settings SET zoneport=@Gustaberg WHERE name='Dangruf_Wadi';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='Inner_Horutoto_Ruins';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Ordelles_Caves';
UPDATE zone_settings SET zoneport=@Sarutabaruta WHERE name='Outer_Horutoto_Ruins';
UPDATE zone_settings SET zoneport=@Movalpolos_Norvallen WHERE name='The_Eldieme_Necropolis';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Gusgen_Mines';
UPDATE zone_settings SET zoneport=@Derfland WHERE name='Crawlers_Nest';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Maze_of_Shakhrami';
UPDATE zone_settings SET zoneport=@Other WHERE name='Residential_Area';
UPDATE zone_settings SET zoneport=@Aragoneu WHERE name='Garlaige_Citadel';
UPDATE zone_settings SET zoneport=@Vollbow WHERE name='Cloister_of_Gales';
UPDATE zone_settings SET zoneport=@Li_Telor WHERE name='Cloister_of_Storms';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='Cloister_of_Frost';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='FeiYin';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Ifrits_Cauldron';
UPDATE zone_settings SET zoneport=@Fauregandi WHERE name='QuBia_Arena';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Cloister_of_Flames';
UPDATE zone_settings SET zoneport=@Kuzotz WHERE name='Quicksand_Caves';
UPDATE zone_settings SET zoneport=@Kuzotz WHERE name='Cloister_of_Tremors';
UPDATE zone_settings SET zoneport=@Other WHERE name='GM_Home';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Cloister_of_Tides';
UPDATE zone_settings SET zoneport=@Vollbow WHERE name='Gustav_Tunnel';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Labyrinth_of_Onzozo';
UPDATE zone_settings SET zoneport=@Other WHERE name='Residential_Area';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Attohwa';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Misareaux';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Vunkerl';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Altepa';
UPDATE zone_settings SET zoneport=@Other WHERE name='Residential_Area';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Ship_bound_for_Selbina';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Ship_bound_for_Mhaura';
UPDATE zone_settings SET zoneport=@Bazaar_and_Jail WHERE name='Provenance';
UPDATE zone_settings SET zoneport=@Sandoria WHERE name='San_dOria-Jeuno_Airship';
UPDATE zone_settings SET zoneport=@Bastok WHERE name='Bastok-Jeuno_Airship';
UPDATE zone_settings SET zoneport=@Windurst WHERE name='Windurst-Jeuno_Airship';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Kazham-Jeuno_Airship';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Ship_bound_for_Selbina_Pirates';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Ship_bound_for_Mhaura_Pirates';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='229';
UPDATE zone_settings SET zoneport=@Sandoria WHERE name='Southern_San_dOria';
UPDATE zone_settings SET zoneport=@Sandoria WHERE name='Northern_San_dOria';
UPDATE zone_settings SET zoneport=@Sandoria WHERE name='Port_San_dOria';
UPDATE zone_settings SET zoneport=@Sandoria WHERE name='Chateau_dOraguille';
UPDATE zone_settings SET zoneport=@Bastok WHERE name='Bastok_Mines';
UPDATE zone_settings SET zoneport=@Bastok WHERE name='Bastok_Markets';
UPDATE zone_settings SET zoneport=@Bastok WHERE name='Port_Bastok';
UPDATE zone_settings SET zoneport=@Bastok WHERE name='Metalworks';
UPDATE zone_settings SET zoneport=@Windurst WHERE name='Windurst_Waters';
UPDATE zone_settings SET zoneport=@Windurst WHERE name='Windurst_Walls';
UPDATE zone_settings SET zoneport=@Windurst WHERE name='Port_Windurst';
UPDATE zone_settings SET zoneport=@Windurst WHERE name='Windurst_Woods';
UPDATE zone_settings SET zoneport=@Windurst WHERE name='Heavens_Tower';
UPDATE zone_settings SET zoneport=@Jeuno WHERE name='RuLude_Gardens';
UPDATE zone_settings SET zoneport=@Jeuno WHERE name='Upper_Jeuno';
UPDATE zone_settings SET zoneport=@Jeuno WHERE name='Lower_Jeuno';
UPDATE zone_settings SET zoneport=@Jeuno WHERE name='Port_Jeuno';
UPDATE zone_settings SET zoneport=@Kuzotz WHERE name='Rabao';
UPDATE zone_settings SET zoneport=@Zulkheim WHERE name='Selbina';
UPDATE zone_settings SET zoneport=@Kolshushu WHERE name='Mhaura';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Kazham';
UPDATE zone_settings SET zoneport=@Tu_Lia WHERE name='Hall_of_the_Gods';
UPDATE zone_settings SET zoneport=@Elshimo WHERE name='Norg';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Uleguerand';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Grauberg';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Abyssea-Empyreal_Paradox';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Western_Adoulin';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Eastern_Adoulin';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Rala_Waterways';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Rala_Waterways_U';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Yahse_Hunting_Grounds';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Ceizak_Battlegrounds';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Foret_de_Hennetiel';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Yorcia_Weald';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Yorcia_Weald_U';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Morimar_Basalt_Fields';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Marjami_Ravine';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Kamihr_Drifts';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Sih_Gates';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Moh_Gates';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Cirdas_Caverns';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Cirdas_Caverns_U';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Dho_Gates';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Woh_Gates';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Outer_RaKaznar';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Outer_RaKaznar_U';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='RaKaznar_Inner_Court';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='RaKaznar_Turris';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='278';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Walk_of_Echoes_[P2]';
UPDATE zone_settings SET zoneport=@Other WHERE name='Mog_Garden';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Leafallia';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Mount_Kamihr';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Silver_Knife';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Celennia_Memorial_Library';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Feretory';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='286';
UPDATE zone_settings SET zoneport=@Abdhaljs WHERE name='Maquette_Abdhaljs-Legion_B';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Escha_ZiTah';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Escha_RuAun';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Desuetia_Empyreal_Paradox';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Reisenjima';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Reisenjima_Henge';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Reisenjima_Sanctorium';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Dynamis-San_dOria_[D]';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Dynamis-Bastok_[D]';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Dynamis-Windurst_[D]';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Dynamis-Jeuno_[D]';
UPDATE zone_settings SET zoneport=@Disabled WHERE name='Walk_of_Echoes_[P1]';