LOCK TABLES 
	`chars` WRITE;

ALTER TABLE `chars` 
    ADD COLUMN IF NOT EXISTS `jail_zone` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0 AFTER `lastupdate`,
    ADD COLUMN IF NOT EXISTS `jail_rot` tinyint(3) UNSIGNED NOT NULL DEFAULT 0 AFTER `jail_zone`,
    ADD COLUMN IF NOT EXISTS `jail_x` float(7,3) NOT NULL DEFAULT 0.000 AFTER `jail_rot`,
    ADD COLUMN IF NOT EXISTS `jail_y` float(7,3) NOT NULL DEFAULT 0.000 AFTER `jail_x`,
    ADD COLUMN IF NOT EXISTS `jail_z` float(7,3) NOT NULL DEFAULT 0.000 AFTER `jail_y`;

UNLOCK TABLES;
