local ID = zones[xi.zone.PORT_SAN_DORIA]

return {
    ['Altiret']      = { event = 559 },
    ['Anoki']        = { event = 519 },
    ['Answald']      = { event = 584 },
    ['Antreneau']    = { messageSpecial = ID.text.ANTRENEAU_READY_TO_EAT },
    ['Apstaule']     = { event = 542 },
    ['Artinien']     = { event = 588 },
    ['Auvare']       = { event = 598 },
    ['Avandale']     = { event = 555 },
    ['Bellue']       = { event = 597 },
    ['Bonarpant']    = { event = 595 },
    ['Bricorsant']   = { event = 570 },
    ['Brifalien']    = { event = 589 },
    ['Callort']      = { event = 557 },
    ['Coribalgeant'] = { event = 599 },
    ['Crilde']       = { event = 569 },
    ['Dabbio']       = { event = 722 },
    ['Diraulate']    = { event = 581 },
    ['Eaugouint']    = { event = 579 },
    ['Eddy']         = { event = 723 },
    ['Fontoumant']   = { event = 561 },
    ['Gournaie']     = { event = 715 },
    ['Gulemont']     = { event = 593 },
    ['Ilgusin']      = { event = 591 },
    ['Jaireto']      = { event = 711 },
    ['Laucimercen']  = { event = 563 },
    ['Liloune']      = { event = 594 },
    ['Marquie']      = { event = 565 },
    ['Maunadolace']  = { event = 713 },
    ['Meta']         = { event = 520 },
    ['Meuxtajean']   = { event = 582 },
    ['Miene']        = { event = 553 },
    ['Noquerelle']   = { event = 583 },
    ['Parcarin']     = { event = 566 },
    ['Phersula']     = { event = 775 },
    ['Portaure']     = { event = 651 },
    ['Prietta']      = { event = 596 },
    ['Rielle']       = { event = 564 },
    ['Sheridan']     = { event = 572 },
    ['Solgierte']    = { event = 567 },
    ['Teilsa']       = { event = 573 },
    ['Thierride']    = { event = 521 },
}
