#USE xidb; #For default installs
USE tpzdb; #Or change to your database name
DELETE FROM `mob_droplist` WHERE `dropId` = 143 AND `itemId` = 3356;
INSERT `mob_droplist` (`dropId`,`dropType`,`groupId`,`groupRate`,`itemId`,`itemRate`) VALUES (143,0,0,1000,3356,260);               
UPDATE `mob_groups` SET `spawnType` = 0 WHERE `zoneId`= 188 AND `dropId` = 143 AND `spawnType`= 32;
DELETE FROM mob_spawn_points WHERE mobid =17547272 AND mobname = 'Vanguard_Pathfinder';
DELETE FROM mob_spawn_points WHERE mobid =17547281 AND mobname = 'Vanguard_Tinkerer';
DELETE FROM mob_spawn_points WHERE mobid =17547284 AND mobname = 'Vanguard_Enchanter';
DELETE FROM mob_spawn_points WHERE mobid =17547288 AND mobname = 'Vanguard_Ronin';
DELETE FROM mob_spawn_points WHERE mobid =17547289 AND mobname = 'Vanguard_Armorer';
DELETE FROM mob_spawn_points WHERE mobid =17547290 AND mobname = 'Vanguard_Hitman';
DELETE FROM mob_spawn_points WHERE mobid =17547304 AND mobname = 'Vanguard_Smithy';
DELETE FROM mob_spawn_points WHERE mobid =17547305 AND mobname = 'Vanguard_Welldigger';
DELETE FROM mob_spawn_points WHERE mobid =17547306 AND mobname = 'Vanguard_Ambusher';
DELETE FROM mob_spawn_points WHERE mobid =17547308 AND mobname = 'Vanguard_Alchemist';
DELETE FROM mob_spawn_points WHERE mobid =17547315 AND mobname = 'Vanguard_Pitfighter';
DELETE FROM mob_spawn_points WHERE mobid =17547317 AND mobname = 'Vanguard_Necromancer';
DELETE FROM mob_spawn_points WHERE mobid =17547320 AND mobname = 'Vanguard_Shaman';
DELETE FROM mob_spawn_points WHERE mobid =17547326 AND mobname = 'Vanguard_Maestro';
DELETE FROM mob_spawn_points WHERE mobid =17547332 AND mobname = 'Vanguard_Dragontamer';
DELETE FROM mob_spawn_points WHERE mobid =17547336 AND mobname = 'Vanguard_Enchanter';
DELETE FROM mob_spawn_points WHERE mobid =17547339 AND mobname = 'Vanguard_Welldigger';
DELETE FROM mob_spawn_points WHERE mobid =17547347 AND mobname = 'Vanguard_Ambusher';
DELETE FROM mob_spawn_points WHERE mobid =17547351 AND mobname = 'Vanguard_Alchemist';
DELETE FROM mob_spawn_points WHERE mobid =17547353 AND mobname = 'Vanguard_Armorer';
DELETE FROM mob_spawn_points WHERE mobid =17547359 AND mobname = 'Vanguard_Maestro';
DELETE FROM mob_spawn_points WHERE mobid =17547363 AND mobname = 'Vanguard_Smithy';
DELETE FROM mob_spawn_points WHERE mobid =17547367 AND mobname = 'Vanguard_Ronin';
DELETE FROM mob_spawn_points WHERE mobid =17547368 AND mobname = 'Vanguard_Hitman';
DELETE FROM mob_spawn_points WHERE mobid =17547369 AND mobname = 'Vanguard_Pathfinder';
DELETE FROM mob_spawn_points WHERE mobid =17547372 AND mobname = 'Vanguard_Shaman';
DELETE FROM mob_spawn_points WHERE mobid =17547375 AND mobname = 'Vanguard_Pitfighter';
DELETE FROM mob_spawn_points WHERE mobid =17547376 AND mobname = 'Vanguard_Tinkerer';
DELETE FROM mob_spawn_points WHERE mobid =17547401 AND mobname = 'Vanguard_Alchemist';
DELETE FROM mob_spawn_points WHERE mobid =17547403 AND mobname = 'Vanguard_Smithy';
DELETE FROM mob_spawn_points WHERE mobid =17547405 AND mobname = 'Vanguard_Welldigger';
DELETE FROM mob_spawn_points WHERE mobid =17547409 AND mobname = 'Vanguard_Pitfighter';
DELETE FROM mob_spawn_points WHERE mobid =17547417 AND mobname = 'Vanguard_Shaman';
DELETE FROM mob_spawn_points WHERE mobid =17547418 AND mobname = 'Vanguard_Enchanter';
DELETE FROM mob_spawn_points WHERE mobid =17547426 AND mobname = 'Vanguard_Dragontamer';
DELETE FROM mob_spawn_points WHERE mobid =17547432 AND mobname = 'Vanguard_Armorer';
DELETE FROM mob_spawn_points WHERE mobid =17547433 AND mobname = 'Vanguard_Maestro';
DELETE FROM mob_spawn_points WHERE mobid =17547435 AND mobname = 'Vanguard_Ronin';
DELETE FROM mob_spawn_points WHERE mobid =17547436 AND mobname = 'Vanguard_Necromancer';
DELETE FROM mob_spawn_points WHERE mobid =17547441 AND mobname = 'Vanguard_Tinkerer';
DELETE FROM mob_spawn_points WHERE mobid =17547461 AND mobname = 'Vanguard_Ambusher';
DELETE FROM mob_spawn_points WHERE mobid =17547462 AND mobname = 'Vanguard_Hitman';
DELETE FROM mob_spawn_points WHERE mobid =17547469 AND mobname = 'Vanguard_Smithy';
DELETE FROM mob_spawn_points WHERE mobid =17547471 AND mobname = 'Vanguard_Welldigger';
DELETE FROM mob_spawn_points WHERE mobid =17547475 AND mobname = 'Vanguard_Alchemist';
DELETE FROM mob_spawn_points WHERE mobid =17547483 AND mobname = 'Vanguard_Pathfinder';
DELETE FROM mob_spawn_points WHERE mobid =17547489 AND mobname = 'Vanguard_Ambusher';
DELETE FROM mob_spawn_points WHERE mobid =17547491 AND mobname = 'Vanguard_Hitman';
