// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables -no-timestamp-warning -fail-on-parse -identity-naming xidb.sql ../src/database xidb
#ifndef XIDB_ACCOUNT_IP_RECORD_H
#define XIDB_ACCOUNT_IP_RECORD_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace xidb
{
  namespace account_ip_record_
  {
    struct login_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "login_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T login_time;
            T& operator()() { return login_time; }
            const T& operator()() const { return login_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point>;
    };
    struct accid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "accid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T accid;
            T& operator()() { return accid; }
            const T& operator()() const { return accid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct charid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "charid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T charid;
            T& operator()() { return charid; }
            const T& operator()() const { return charid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct client_ip
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "client_ip";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T client_ip;
            T& operator()() { return client_ip; }
            const T& operator()() const { return client_ip; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace account_ip_record_

  struct account_ip_record: sqlpp::table_t<account_ip_record,
               account_ip_record_::login_time,
               account_ip_record_::accid,
               account_ip_record_::charid,
               account_ip_record_::client_ip>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "account_ip_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T account_ip_record;
        T& operator()() { return account_ip_record; }
        const T& operator()() const { return account_ip_record; }
      };
    };
  };
} // namespace xidb
#endif
