// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables -no-timestamp-warning -fail-on-parse -identity-naming xidb.sql ../src/database xidb
#ifndef XIDB_AUTOMATON_SPELLS_H
#define XIDB_AUTOMATON_SPELLS_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace xidb
{
  namespace automaton_spells_
  {
    struct spellid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "spellid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T spellid;
            T& operator()() { return spellid; }
            const T& operator()() const { return spellid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned, sqlpp::tag::can_be_null>;
    };
    struct skilllevel
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "skilllevel";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T skilllevel;
            T& operator()() { return skilllevel; }
            const T& operator()() const { return skilllevel; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned>;
    };
    struct heads
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "heads";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T heads;
            T& operator()() { return heads; }
            const T& operator()() const { return heads; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct enfeeble
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "enfeeble";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T enfeeble;
            T& operator()() { return enfeeble; }
            const T& operator()() const { return enfeeble; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned>;
    };
    struct immunity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "immunity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T immunity;
            T& operator()() { return immunity; }
            const T& operator()() const { return immunity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned>;
    };
    struct removes
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "removes";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T removes;
            T& operator()() { return removes; }
            const T& operator()() const { return removes; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer_unsigned>;
    };
  } // namespace automaton_spells_

  struct automaton_spells: sqlpp::table_t<automaton_spells,
               automaton_spells_::spellid,
               automaton_spells_::skilllevel,
               automaton_spells_::heads,
               automaton_spells_::enfeeble,
               automaton_spells_::immunity,
               automaton_spells_::removes>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "automaton_spells";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T automaton_spells;
        T& operator()() { return automaton_spells; }
        const T& operator()() const { return automaton_spells; }
      };
    };
  };
} // namespace xidb
#endif
