// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables xidb.sql ../src/database xidb
#ifndef XIDB_BCNM_TREASURE_CHESTS_H
#define XIDB_BCNM_TREASURE_CHESTS_H

#include <sqlpp11/char_sequence.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/table.h>

namespace xidb
{
    namespace BcnmTreasureChests_
    {
        struct BcnmId
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "bcnmId";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  bcnmId;
                    T& operator()()
                    {
                        return bcnmId;
                    }
                    const T& operator()() const
                    {
                        return bcnmId;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned, sqlpp::tag::can_be_null>;
        };
        struct BattlefieldNumber
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "battlefieldNumber";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  battlefieldNumber;
                    T& operator()()
                    {
                        return battlefieldNumber;
                    }
                    const T& operator()() const
                    {
                        return battlefieldNumber;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::tinyint, sqlpp::tag::can_be_null>;
        };
        struct NpcId
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "npcId";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  npcId;
                    T& operator()()
                    {
                        return npcId;
                    }
                    const T& operator()() const
                    {
                        return npcId;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
        };
    } // namespace BcnmTreasureChests_

    struct BcnmTreasureChests : sqlpp::table_t<BcnmTreasureChests,
                                               BcnmTreasureChests_::BcnmId,
                                               BcnmTreasureChests_::BattlefieldNumber,
                                               BcnmTreasureChests_::NpcId>
    {
        struct _alias_t
        {
            static constexpr const char _literal[] = "bcnm_treasure_chests";
            using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
            template <typename T>
            struct _member_t
            {
                T  bcnmTreasureChests;
                T& operator()()
                {
                    return bcnmTreasureChests;
                }
                const T& operator()() const
                {
                    return bcnmTreasureChests;
                }
            };
        };
    };
} // namespace xidb
#endif
