// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables -no-timestamp-warning -fail-on-parse -identity-naming xidb.sql ../src/database xidb
#ifndef XIDB_BLUE_SPELL_MODS_H
#define XIDB_BLUE_SPELL_MODS_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace xidb
{
  namespace blue_spell_mods_
  {
    struct spellId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "spellId";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T spellId;
            T& operator()() { return spellId; }
            const T& operator()() const { return spellId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned, sqlpp::tag::can_be_null>;
    };
    struct modid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "modid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T modid;
            T& operator()() { return modid; }
            const T& operator()() const { return modid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned, sqlpp::tag::can_be_null>;
    };
    struct value
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "value";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T value;
            T& operator()() { return value; }
            const T& operator()() const { return value; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint>;
    };
  } // namespace blue_spell_mods_

  struct blue_spell_mods: sqlpp::table_t<blue_spell_mods,
               blue_spell_mods_::spellId,
               blue_spell_mods_::modid,
               blue_spell_mods_::value>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "blue_spell_mods";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T blue_spell_mods;
        T& operator()() { return blue_spell_mods; }
        const T& operator()() const { return blue_spell_mods; }
      };
    };
  };
} // namespace xidb
#endif
