// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables -no-timestamp-warning -fail-on-parse -identity-naming xidb.sql ../src/database xidb
#ifndef XIDB_FISHING_ROD_H
#define XIDB_FISHING_ROD_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace xidb
{
  namespace fishing_rod_
  {
    struct rodid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "rodid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T rodid;
            T& operator()() { return rodid; }
            const T& operator()() const { return rodid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned, sqlpp::tag::can_be_null>;
    };
    struct name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct fishid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "fishid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T fishid;
            T& operator()() { return fishid; }
            const T& operator()() const { return fishid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned, sqlpp::tag::can_be_null>;
    };
    struct flag
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "flag";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T flag;
            T& operator()() { return flag; }
            const T& operator()() const { return flag; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer_unsigned, sqlpp::tag::can_be_null>;
    };
  } // namespace fishing_rod_

  struct fishing_rod: sqlpp::table_t<fishing_rod,
               fishing_rod_::rodid,
               fishing_rod_::name,
               fishing_rod_::fishid,
               fishing_rod_::flag>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "fishing_rod";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T fishing_rod;
        T& operator()() { return fishing_rod; }
        const T& operator()() const { return fishing_rod; }
      };
    };
  };
} // namespace xidb
#endif
