// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables xidb.sql ../src/database xidb
#ifndef XIDB_ITEM_FURNISHING_H
#define XIDB_ITEM_FURNISHING_H

#include <sqlpp11/char_sequence.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/table.h>

namespace xidb
{
    namespace ItemFurnishing_
    {
        struct Itemid
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "itemid";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  itemid;
                    T& operator()()
                    {
                        return itemid;
                    }
                    const T& operator()() const
                    {
                        return itemid;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned, sqlpp::tag::can_be_null>;
        };
        struct Name
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "name";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  name;
                    T& operator()()
                    {
                        return name;
                    }
                    const T& operator()() const
                    {
                        return name;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
        };
        struct Storage
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "storage";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  storage;
                    T& operator()()
                    {
                        return storage;
                    }
                    const T& operator()() const
                    {
                        return storage;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
        };
        struct Moghancement
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "moghancement";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  moghancement;
                    T& operator()()
                    {
                        return moghancement;
                    }
                    const T& operator()() const
                    {
                        return moghancement;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::smallint_unsigned>;
        };
        struct Element
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "element";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  element;
                    T& operator()()
                    {
                        return element;
                    }
                    const T& operator()() const
                    {
                        return element;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
        };
        struct Aura
        {
            struct _alias_t
            {
                static constexpr const char _literal[] = "aura";
                using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
                template <typename T>
                struct _member_t
                {
                    T  aura;
                    T& operator()()
                    {
                        return aura;
                    }
                    const T& operator()() const
                    {
                        return aura;
                    }
                };
            };
            using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
        };
    } // namespace ItemFurnishing_

    struct ItemFurnishing : sqlpp::table_t<ItemFurnishing,
                                           ItemFurnishing_::Itemid,
                                           ItemFurnishing_::Name,
                                           ItemFurnishing_::Storage,
                                           ItemFurnishing_::Moghancement,
                                           ItemFurnishing_::Element,
                                           ItemFurnishing_::Aura>
    {
        struct _alias_t
        {
            static constexpr const char _literal[] = "item_furnishing";
            using _name_t                          = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
            template <typename T>
            struct _member_t
            {
                T  itemFurnishing;
                T& operator()()
                {
                    return itemFurnishing;
                }
                const T& operator()() const
                {
                    return itemFurnishing;
                }
            };
        };
    };
} // namespace xidb
#endif
