// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables -no-timestamp-warning -fail-on-parse -identity-naming xidb.sql ../src/database xidb
#ifndef XIDB_JOB_POINT_GIFTS_H
#define XIDB_JOB_POINT_GIFTS_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace xidb
{
  namespace job_point_gifts_
  {
    struct jobid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "jobid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T jobid;
            T& operator()() { return jobid; }
            const T& operator()() const { return jobid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint, sqlpp::tag::can_be_null>;
    };
    struct jp_needed
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "jp_needed";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T jp_needed;
            T& operator()() { return jp_needed; }
            const T& operator()() const { return jp_needed; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint>;
    };
    struct modid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "modid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T modid;
            T& operator()() { return modid; }
            const T& operator()() const { return modid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::smallint>;
    };
    struct value
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "value";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T value;
            T& operator()() { return value; }
            const T& operator()() const { return value; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint>;
    };
    struct desc
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "desc";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T desc;
            T& operator()() { return desc; }
            const T& operator()() const { return desc; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text>;
    };
  } // namespace job_point_gifts_

  struct job_point_gifts: sqlpp::table_t<job_point_gifts,
               job_point_gifts_::jobid,
               job_point_gifts_::jp_needed,
               job_point_gifts_::modid,
               job_point_gifts_::value,
               job_point_gifts_::desc>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "job_point_gifts";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T job_point_gifts;
        T& operator()() { return job_point_gifts; }
        const T& operator()() const { return job_point_gifts; }
      };
    };
  };
} // namespace xidb
#endif
