// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables -no-timestamp-warning -fail-on-parse -identity-naming xidb.sql ../src/database xidb
#ifndef XIDB_NM_SPAWN_POINTS_H
#define XIDB_NM_SPAWN_POINTS_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace xidb
{
  namespace nm_spawn_points_
  {
    struct mobid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mobid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mobid;
            T& operator()() { return mobid; }
            const T& operator()() const { return mobid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct pos
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pos";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pos;
            T& operator()() { return pos; }
            const T& operator()() const { return pos; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct pos_x
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pos_x";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pos_x;
            T& operator()() { return pos_x; }
            const T& operator()() const { return pos_x; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point>;
    };
    struct pos_y
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pos_y";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pos_y;
            T& operator()() { return pos_y; }
            const T& operator()() const { return pos_y; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point>;
    };
    struct pos_z
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pos_z";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pos_z;
            T& operator()() { return pos_z; }
            const T& operator()() const { return pos_z; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point>;
    };
  } // namespace nm_spawn_points_

  struct nm_spawn_points: sqlpp::table_t<nm_spawn_points,
               nm_spawn_points_::mobid,
               nm_spawn_points_::pos,
               nm_spawn_points_::pos_x,
               nm_spawn_points_::pos_y,
               nm_spawn_points_::pos_z>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "nm_spawn_points";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T nm_spawn_points;
        T& operator()() { return nm_spawn_points; }
        const T& operator()() const { return nm_spawn_points; }
      };
    };
  };
} // namespace xidb
#endif
