// generated by C:/ffxi/server/build/_deps/sqlpp11-src/scripts/ddl2cpp -split-tables -no-timestamp-warning -fail-on-parse -identity-naming xidb.sql ../src/database xidb
#ifndef XIDB_SKILL_RANKS_H
#define XIDB_SKILL_RANKS_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace xidb
{
  namespace skill_ranks_
  {
    struct skillid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "skillid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T skillid;
            T& operator()() { return skillid; }
            const T& operator()() const { return skillid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::char_, sqlpp::tag::can_be_null>;
    };
    struct war
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "war";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T war;
            T& operator()() { return war; }
            const T& operator()() const { return war; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct mnk
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mnk";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mnk;
            T& operator()() { return mnk; }
            const T& operator()() const { return mnk; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct whm
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "whm";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T whm;
            T& operator()() { return whm; }
            const T& operator()() const { return whm; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct blm
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "blm";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T blm;
            T& operator()() { return blm; }
            const T& operator()() const { return blm; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct rdm
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "rdm";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T rdm;
            T& operator()() { return rdm; }
            const T& operator()() const { return rdm; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct thf
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "thf";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T thf;
            T& operator()() { return thf; }
            const T& operator()() const { return thf; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct pld
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pld";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pld;
            T& operator()() { return pld; }
            const T& operator()() const { return pld; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct drk
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "drk";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T drk;
            T& operator()() { return drk; }
            const T& operator()() const { return drk; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct bst
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "bst";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T bst;
            T& operator()() { return bst; }
            const T& operator()() const { return bst; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct brd
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "brd";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T brd;
            T& operator()() { return brd; }
            const T& operator()() const { return brd; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct rng
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "rng";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T rng;
            T& operator()() { return rng; }
            const T& operator()() const { return rng; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct sam
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "sam";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T sam;
            T& operator()() { return sam; }
            const T& operator()() const { return sam; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct nin
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "nin";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T nin;
            T& operator()() { return nin; }
            const T& operator()() const { return nin; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct drg
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "drg";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T drg;
            T& operator()() { return drg; }
            const T& operator()() const { return drg; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct smn
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "smn";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T smn;
            T& operator()() { return smn; }
            const T& operator()() const { return smn; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct blu
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "blu";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T blu;
            T& operator()() { return blu; }
            const T& operator()() const { return blu; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct cor
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "cor";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T cor;
            T& operator()() { return cor; }
            const T& operator()() const { return cor; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct pup
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pup";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pup;
            T& operator()() { return pup; }
            const T& operator()() const { return pup; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct dnc
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "dnc";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T dnc;
            T& operator()() { return dnc; }
            const T& operator()() const { return dnc; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct sch
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "sch";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T sch;
            T& operator()() { return sch; }
            const T& operator()() const { return sch; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct geo
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "geo";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T geo;
            T& operator()() { return geo; }
            const T& operator()() const { return geo; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
    struct run
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "run";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T run;
            T& operator()() { return run; }
            const T& operator()() const { return run; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::tinyint_unsigned>;
    };
  } // namespace skill_ranks_

  struct skill_ranks: sqlpp::table_t<skill_ranks,
               skill_ranks_::skillid,
               skill_ranks_::name,
               skill_ranks_::war,
               skill_ranks_::mnk,
               skill_ranks_::whm,
               skill_ranks_::blm,
               skill_ranks_::rdm,
               skill_ranks_::thf,
               skill_ranks_::pld,
               skill_ranks_::drk,
               skill_ranks_::bst,
               skill_ranks_::brd,
               skill_ranks_::rng,
               skill_ranks_::sam,
               skill_ranks_::nin,
               skill_ranks_::drg,
               skill_ranks_::smn,
               skill_ranks_::blu,
               skill_ranks_::cor,
               skill_ranks_::pup,
               skill_ranks_::dnc,
               skill_ranks_::sch,
               skill_ranks_::geo,
               skill_ranks_::run>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "skill_ranks";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T skill_ranks;
        T& operator()() { return skill_ranks; }
        const T& operator()() const { return skill_ranks; }
      };
    };
  };
} // namespace xidb
#endif
