-- NOTE: This file is autogenerated!
-- You can (and should) change the values in here to whatever you desire.
-- If you want to add new settings, go look at tools/generate_settings.py

xi = xi or {}
xi.settings = xi.settings or {}

xi.settings.main =
{
    SERVER_NAME = "Nameless", -- (string) The name of the server
    ENABLE_COP = true, -- (bool) Enables expansion: Chains of Promathia
    ENABLE_TOAU = true, -- (bool) Enables expansion: Treasure of Aht Urghan
    ENABLE_WOTG = true, -- (bool) Enables expansion: Wings of the Goddess
    ENABLE_ACP = true, -- (bool) Enables mini-expansion: A Crystaline Prophecy
    ENABLE_AMK = true, -- (bool) Enables mini-expansion: A Moogle Kupo d'Etat
    ENABLE_ASA = true, -- (bool) Enables mini-expansion: A Shantotto Ascenscion
    ENABLE_ABYSSEA = true, -- (bool) Enables expansion: Abyssea
    ENABLE_SOA = true, -- (bool) Enables expansion: Seekers of Adoulin
    ENABLE_ROV = true, -- (bool) Enables expansion: Rhapsodies of Vana'diel
    ENABLE_VOIDWATCH = true, -- (bool) Enables Voidwatch (Not an expansion
    DAMAGE_MULT = 1.0, -- (float) The multiplier applied to all damage directed towards players
}
