-- NOTE: This file is autogenerated!
-- You can (and should) change the values in here to whatever you desire.
-- If you want to add new settings, go look at tools/generate_settings.py

xi = xi or {}
xi.settings = xi.settings or {}

xi.settings.maintenance =
{
    MAINT_MODE = false, -- (bool) False: Normal operation. True: only GM characters allowed online & no new character creation

}
