local ID = zones[xi.zone.WINDURST_WATERS_S]

return {
    ['Adjutant']        = { event = 305 },
    ['Aihn_Sowlmirih']  = { event = 412 },
    ['Amfafa']          = { event = 433 },
    ['Ampiro-Mapiro']   = { event = 423 },
    ['Aystise']         = { event = 410 },
    ['Cattah Pamjah']   = { event = 137 },
    ['Chays-Ratays']    = { event = 401 },
    ['Churacoco']       = { event = 434 },
    ['Corbrere']        = { event = 414 },
    ['Dallus-Mallus']   = { event = 323 },
    ['Eih_Lhogotan']    = { event = 407 },
    ['Ekki-Mokki']      = { event = 409 },
    ['Emhi_Tchaoryo']   = { event = 307 },
    ['Gevarg']          = { event = 0 },
    ['Khea_Mhyyih']     = { event = 428 },
    ['Kleh_Engyumoh']   = { event = 431 },
    ['Kolin-Olin']      = { event = 306 },
    ['Kopol-Rapol']     = { event = 422 },
    ['Koton-Llaton']    = { event = 402 },
    ['Kristen']         = { event = 404 },
    ['Kuron-Makaron']   = { event = 300 },
    ['Llewellyn']       = { event = 10 },
    ['Lutete']          = { text = ID.text.LUTETE_DIALOG },
    ['Mearuru']         = { event = 418 },
    ['Mhoti_Pyiahrs']   = { event = 2 },
    ['Mikhe Aryohcha']  = { text = ID.text.MIKHE_ARYOHCHA_DIALOG },
    ['Narito-Pettito']  = { event = 425 },
    ['Nhel_Urhahn']     = { event = 416 },
    ['Ozzmo-Mazmo']     = { event = 432 },
    ['Pahpe_Rauulih']   = { event = 427 },
    ['Parukoko']        = { event = 436 },
    ['Pebul-Tabul']     = { event = 405 },
    ['Pelsey-Holsey']   = { event = 419 },
    ['Pettette']        = { event = 9 },
    ['Pogigi']          = { event = 330 },
    ['Ponono']          = { event = 193 },
    ['Prucco-Lurucco']  = { event = 420 },
    ['Quartermaster']   = { event = 201 },
    ['Ragyaya']         = { event = 406 },
    ['Rakh_Mhappyoh']   = { event = 411 },
    ['Rakih_Lyhall']    = { event = 429 },
    ['Ranna-Brunna']    = { event = 424 },
    ['Ransnana']        = { event = 408 },
    ['Renten-Tonten']   = { event = 421 },
    ['Romaa_Mihgo']     = { event = 11 },
    ['Ruirara']         = { event = 435 },
    ['Sahnn_Dhansett']  = { event = 417 },
    ['Scotwick']        = { event = 16 },
    ['Soimin-Oimin_CC'] = { event = 452 },
    ['Tahl_Mhioguch']   = { event = 438 },
    ['Tohs_Jhannih']    = { event = 430 },
    ['Upital-Lupital']  = { event = 439 },
    ['Uricca-Koricca']  = { event = 437 },
    ['Velda-Galda']     = { event = 177 },
    ['Wenonah_CA']      = { event = 459 },
}
