local ID = zones[xi.zone.NORG]

return {
    ['_700']        = { messageSpecial = ID.text.DOOR_IS_LOCKED },
    ['Aeka']        = { event = 120 },
    ['Ailee']       = { event = 91 },
    ['Andrause']    = { event = 239 },
    ['Colleraie']   = { event = 175 },
    ['Comitiolus']  = { event = 72 },
    ['Corlotte']    = { event = 73 },
    ['Deigoff']     = { event = 86 },
    ['Enishi']      = { event = 77 },
    ['Eunsoo']      = { event = 63 },
    ['Gabide']      = { event = 78 },
    ['Gottna']      = { event = 66 },
    ['Hayris']      = { event = 215 },
    ['Heillal']     = { event = 64 },
    ['Jaucribaix']  = { event = 71 },
    ['Kamui']       = { event = 61 },
    ['Keal']        = { event = 89 },
    ['Koetsu']      = { event = 70 },
    ['Laisrean']    = { event = 83 },
    ['Louartain']   = { event = 84 },
    ['Ludiault']    = { event = 82 },
    ['Odilinia']    = { event = 92 },
    ['Ogugu']       = { event = 79 },
    ['Oruga']       = { event = 87 },
    ['Paito-Maito'] = { event = 90 },
    ['Parlemaille'] = { event = 88 },
    ['Rafid']       = { event = 65 },
    ['Ramon']       = { event = 62 },
    ['Ranemaud']    = { event = 68 },
    ['Ryoma']       = { event = 94 },
    ['Shivivi']     = { event = 85 },
    ['Sohyon']      = { event = 212 },
    ['Verctissa']   = { event = 114 },
    ['Vishwas']     = { event = 218 },
    ['Washu']       = { event = 80 },
}
