return {
    ['Amalanbraux']      = { event = 700 },
    ['Galdo']            = { event = 650 },
    ['Hagain']           = { event = 10002 },
    ['Itzha_Delavhitta'] = { event = 900 },
    ['Jikka-Abukka']     = { event = 850 },
    ['Koh_Lenbalalako']  = { event = 10013 },
    ['Kotan-Purutan']    = { event = 140 },
    ['Kupupu']           = { event = 800 },
    ['Lacia']            = { event = 10021 },
    ['Lakom-Lukom']      = { event = 600 },
    ['Numi_Adaligo']     = { event = 50 },
    ['Phoochuchu']       = { event = 300 },
    ['Rycharde']         = { event = 69 },
    ['Take']             = { event = 59 },
    ['Tonasav']          = { event = 372 },
    ['Zhon_Kihshimo']    = { event = 25 },
    ['Zexu']             = { event = 121 },
    ['Blandine']         = { event = 122 },
    ['Katsunaga']        = { event = 190 },
}
