#USE xidb; # For defaul installs
USE tpzdb; #Or change to your database name
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =6 AND `zoneid`=10 AND `name`='Diabolos_HTBF';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =3 AND `zoneid`=16 AND `name`='Idle_Wanderer';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =22 AND `zoneid`=16 AND `name`='Woeful_Weeper';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =23 AND `zoneid`=16 AND `name`='Livid_Seether';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =2 AND `zoneid`=18 AND `name`='Idle_Wanderer';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =22 AND `zoneid`=18 AND `name`='Woeful_Weeper';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =23 AND `zoneid`=18 AND `name`='Livid_Seether';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =3 AND `zoneid`=20 AND `name`='Idle_Wanderer';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =22 AND `zoneid`=20 AND `name`='Woeful_Weeper';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =23 AND `zoneid`=20 AND `name`='Livid_Seether';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =7 AND `zoneid`=22 AND `name`='Idle_Wanderer';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =37 AND `zoneid`=22 AND `name`='Livid_Seether';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =38 AND `zoneid`=22 AND `name`='Woeful_Weeper';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =31 AND `zoneid`=24 AND `name`='Abraxas';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =35 AND `zoneid`=24 AND `name`='Tavnazian_Ram';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =26 AND `zoneid`=25 AND `name`='Seaboard_Vulture';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =44 AND `zoneid`=27 AND `name`='Aqueduct_Spider';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =41 AND `zoneid`=28 AND `name`='Aqueduct_Spider';
UPDATE `mob_groups` SET minLevel=45,maxLevel=45 WHERE `groupid` =9 AND `zoneid`=29 AND `name`='Blazedrake';
UPDATE `mob_groups` SET minLevel=45,maxLevel=45 WHERE `groupid` =13 AND `zoneid`=30 AND `name`='Darner';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =15 AND `zoneid`=31 AND `name`='Ouryu_htbf';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =8 AND `zoneid`=32 AND `name`='Omega_HTBF';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =9 AND `zoneid`=32 AND `name`='Ultima_HTBF';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =88 AND `zoneid`=39 AND `name`='Nightmare_Goobbue';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =89 AND `zoneid`=39 AND `name`='Nightmare_Sabotender';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =90 AND `zoneid`=39 AND `name`='Nightmare_Flytrap';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =91 AND `zoneid`=39 AND `name`='Nightmare_Manticore';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =92 AND `zoneid`=39 AND `name`='Nightmare_Hippogryph';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =93 AND `zoneid`=39 AND `name`='Nightmare_Treant';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =94 AND `zoneid`=39 AND `name`='Nightmare_Funguar';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =95 AND `zoneid`=39 AND `name`='Nightmare_Sheep';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =96 AND `zoneid`=39 AND `name`='Nightmare_Fly';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =97 AND `zoneid`=39 AND `name`='Vanguard_Footsoldier';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =98 AND `zoneid`=39 AND `name`='Vanguard_Pillager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =99 AND `zoneid`=39 AND `name`='Vanguard_Neckchopper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =100 AND `zoneid`=39 AND `name`='Vanguard_Bugler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =101 AND `zoneid`=39 AND `name`='Vanguard_Dollmaster';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =102 AND `zoneid`=39 AND `name`='Vanguards_Avatar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =103 AND `zoneid`=39 AND `name`='Vanguard_Grappler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =104 AND `zoneid`=39 AND `name`='Vanguard_Mesmerizer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =105 AND `zoneid`=39 AND `name`='Vanguard_Predator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =106 AND `zoneid`=39 AND `name`='Vanguard_Backstabber';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =107 AND `zoneid`=39 AND `name`='Vanguard_Hawker';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =108 AND `zoneid`=39 AND `name`='Vanguards_Hecteyes';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =109 AND `zoneid`=39 AND `name`='Vanguard_Amputator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =110 AND `zoneid`=39 AND `name`='Vanguard_Vexer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =111 AND `zoneid`=39 AND `name`='Vanguard_Trooper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =112 AND `zoneid`=39 AND `name`='Vanguard_Gutslasher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =113 AND `zoneid`=39 AND `name`='Vanguard_Impaler';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =114 AND `zoneid`=39 AND `name`='Vanguards_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =117 AND `zoneid`=39 AND `name`='Vanguard_Vindicator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =118 AND `zoneid`=39 AND `name`='Vanguard_Vigilante';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =119 AND `zoneid`=39 AND `name`='Vanguard_Kusa';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =120 AND `zoneid`=39 AND `name`='Vanguard_Militant';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =121 AND `zoneid`=39 AND `name`='Vanguard_Mason';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =122 AND `zoneid`=39 AND `name`='Vanguard_Beasttender';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =123 AND `zoneid`=39 AND `name`='Vanguards_Scorpion';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =124 AND `zoneid`=39 AND `name`='Vanguard_Constable';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =125 AND `zoneid`=39 AND `name`='Vanguard_Purloiner';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =126 AND `zoneid`=39 AND `name`='Vanguard_Drakekeeper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =127 AND `zoneid`=39 AND `name`='Vanguard_Thaumaturge';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =128 AND `zoneid`=39 AND `name`='Vanguard_Minstrel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =129 AND `zoneid`=39 AND `name`='Vanguard_Hatamoto';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =130 AND `zoneid`=39 AND `name`='Vanguard_Protector';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =131 AND `zoneid`=39 AND `name`='Vanguard_Defender';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =132 AND `zoneid`=39 AND `name`='Vanguard_Undertaker';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =135 AND `zoneid`=39 AND `name`='Vanguard_Skirmisher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =136 AND `zoneid`=39 AND `name`='Vanguard_Visionary';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =137 AND `zoneid`=39 AND `name`='Vanguard_Chanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =138 AND `zoneid`=39 AND `name`='Vanguard_Oracle';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =139 AND `zoneid`=39 AND `name`='Vanguard_Sentinel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =140 AND `zoneid`=39 AND `name`='Vanguard_Liberator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =141 AND `zoneid`=39 AND `name`='Vanguard_Salvager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =142 AND `zoneid`=39 AND `name`='Vanguard_Priest';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =143 AND `zoneid`=39 AND `name`='Vanguard_Exemplar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =144 AND `zoneid`=39 AND `name`='Vanguard_Persecutor';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =145 AND `zoneid`=39 AND `name`='Vanguard_Partisan';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =146 AND `zoneid`=39 AND `name`='Vanguard_Prelate';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =147 AND `zoneid`=39 AND `name`='Vanguard_Inciter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =148 AND `zoneid`=39 AND `name`='Vanguard_Assassin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =149 AND `zoneid`=39 AND `name`='Vanguard_Ogresoother';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =150 AND `zoneid`=39 AND `name`='Vanguards_Crow';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =153 AND `zoneid`=39 AND `name`='Vanguard_Smithy';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =154 AND `zoneid`=39 AND `name`='Vanguard_Pitfighter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =155 AND `zoneid`=39 AND `name`='Vanguard_Alchemist';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =156 AND `zoneid`=39 AND `name`='Vanguard_Ambusher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =157 AND `zoneid`=39 AND `name`='Vanguard_Necromancer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =158 AND `zoneid`=39 AND `name`='Vanguard_Shaman';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =159 AND `zoneid`=39 AND `name`='Vanguard_Enchanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =160 AND `zoneid`=39 AND `name`='Vanguard_Welldigger';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =161 AND `zoneid`=39 AND `name`='Vanguard_Ronin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =162 AND `zoneid`=39 AND `name`='Vanguard_Pathfinder';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =163 AND `zoneid`=39 AND `name`='Vanguards_Slime';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =164 AND `zoneid`=39 AND `name`='Vanguard_Armorer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =165 AND `zoneid`=39 AND `name`='Vanguard_Tinkerer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =166 AND `zoneid`=39 AND `name`='Vanguard_Maestro';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =167 AND `zoneid`=39 AND `name`='Vanguard_Hitman';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =170 AND `zoneid`=39 AND `name`='Vanguard_Dragontamer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =111 AND `zoneid`=40 AND `name`='Vanguard_Pitfighter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =112 AND `zoneid`=40 AND `name`='Vanguard_Enchanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =113 AND `zoneid`=40 AND `name`='Vanguard_Welldigger';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =114 AND `zoneid`=40 AND `name`='Vanguard_Armorer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =115 AND `zoneid`=40 AND `name`='Vanguard_Pathfinder';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =116 AND `zoneid`=40 AND `name`='Vanguards_Slime';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =117 AND `zoneid`=40 AND `name`='Vanguard_Maestro';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =118 AND `zoneid`=40 AND `name`='Vanguard_Ronin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =119 AND `zoneid`=40 AND `name`='Vanguard_Necromancer';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =120 AND `zoneid`=40 AND `name`='Vanguards_Avatar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =123 AND `zoneid`=40 AND `name`='Vanguard_Smithy';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =124 AND `zoneid`=40 AND `name`='Vanguard_Alchemist';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =125 AND `zoneid`=40 AND `name`='Vanguard_Shaman';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =126 AND `zoneid`=40 AND `name`='Vanguard_Tinkerer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =127 AND `zoneid`=40 AND `name`='Vanguard_Ambusher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =128 AND `zoneid`=40 AND `name`='Vanguard_Hitman';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =129 AND `zoneid`=40 AND `name`='Vanguard_Dragontamer';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =130 AND `zoneid`=40 AND `name`='Vanguards_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =132 AND `zoneid`=40 AND `name`='Vanguard_Mesmerizer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =133 AND `zoneid`=40 AND `name`='Vanguard_Vexer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =134 AND `zoneid`=40 AND `name`='Vanguard_Pillager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =135 AND `zoneid`=40 AND `name`='Vanguard_Neckchopper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =136 AND `zoneid`=40 AND `name`='Vanguard_Hawker';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =137 AND `zoneid`=40 AND `name`='Vanguards_Hecteyes';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =138 AND `zoneid`=40 AND `name`='Vanguard_Bugler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =139 AND `zoneid`=40 AND `name`='Vanguard_Backstabber';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =140 AND `zoneid`=40 AND `name`='Vanguard_Impaler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =143 AND `zoneid`=40 AND `name`='Vanguard_Footsoldier';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =144 AND `zoneid`=40 AND `name`='Vanguard_Grappler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =145 AND `zoneid`=40 AND `name`='Vanguard_Amputator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =146 AND `zoneid`=40 AND `name`='Vanguard_Predator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =147 AND `zoneid`=40 AND `name`='Vanguard_Trooper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =148 AND `zoneid`=40 AND `name`='Vanguard_Gutslasher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =149 AND `zoneid`=40 AND `name`='Vanguard_Dollmaster';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =150 AND `zoneid`=40 AND `name`='Vanguard_Vindicator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =151 AND `zoneid`=40 AND `name`='Vanguard_Militant';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =152 AND `zoneid`=40 AND `name`='Vanguard_Constable';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =153 AND `zoneid`=40 AND `name`='Vanguard_Beasttender';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =154 AND `zoneid`=40 AND `name`='Vanguards_Scorpion';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =155 AND `zoneid`=40 AND `name`='Vanguard_Minstrel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =156 AND `zoneid`=40 AND `name`='Vanguard_Mason';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =157 AND `zoneid`=40 AND `name`='Vanguard_Drakekeeper';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =159 AND `zoneid`=40 AND `name`='Adamantking_Image';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =160 AND `zoneid`=40 AND `name`='Vanguard_Thaumaturge';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =161 AND `zoneid`=40 AND `name`='Vanguard_Protector';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =162 AND `zoneid`=40 AND `name`='Vanguard_Purloiner';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =163 AND `zoneid`=40 AND `name`='Vanguard_Defender';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =164 AND `zoneid`=40 AND `name`='Vanguard_Vigilante';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =165 AND `zoneid`=40 AND `name`='Vanguard_Hatamoto';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =166 AND `zoneid`=40 AND `name`='Vanguard_Kusa';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =167 AND `zoneid`=40 AND `name`='Vanguard_Undertaker';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =168 AND `zoneid`=40 AND `name`='Vanguard_Sentinel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =169 AND `zoneid`=40 AND `name`='Vanguard_Priest';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =170 AND `zoneid`=40 AND `name`='Vanguard_Liberator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =171 AND `zoneid`=40 AND `name`='Vanguard_Exemplar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =172 AND `zoneid`=40 AND `name`='Vanguard_Ogresoother';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =173 AND `zoneid`=40 AND `name`='Vanguards_Crow';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =174 AND `zoneid`=40 AND `name`='Vanguard_Chanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =175 AND `zoneid`=40 AND `name`='Vanguard_Persecutor';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =176 AND `zoneid`=40 AND `name`='Vanguard_Partisan';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =179 AND `zoneid`=40 AND `name`='Vanguard_Skirmisher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =180 AND `zoneid`=40 AND `name`='Vanguard_Prelate';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =181 AND `zoneid`=40 AND `name`='Vanguard_Visionary';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =182 AND `zoneid`=40 AND `name`='Vanguard_Inciter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =183 AND `zoneid`=40 AND `name`='Vanguard_Salvager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =184 AND `zoneid`=40 AND `name`='Vanguard_Assassin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =185 AND `zoneid`=40 AND `name`='Vanguard_Oracle';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =186 AND `zoneid`=40 AND `name`='Nightmare_Crab';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =187 AND `zoneid`=40 AND `name`='Nightmare_Dhalmel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =188 AND `zoneid`=40 AND `name`='Nightmare_Uragnite';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =189 AND `zoneid`=40 AND `name`='Nightmare_Scorpion';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =190 AND `zoneid`=40 AND `name`='Nightmare_Bunny';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =191 AND `zoneid`=40 AND `name`='Nightmare_Mandragora';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =192 AND `zoneid`=40 AND `name`='Nightmare_Crawler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =193 AND `zoneid`=40 AND `name`='Nightmare_Raven';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =194 AND `zoneid`=40 AND `name`='Nightmare_Eft';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =89 AND `zoneid`=41 AND `name`='Vanguard_Thaumaturge';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =90 AND `zoneid`=41 AND `name`='Vanguard_Oracle';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =94 AND `zoneid`=41 AND `name`='Nightmare_Roc';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =95 AND `zoneid`=41 AND `name`='Nightmare_Stirge';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =96 AND `zoneid`=41 AND `name`='Nightmare_Diremite';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =97 AND `zoneid`=41 AND `name`='Nightmare_Gaylas';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =98 AND `zoneid`=41 AND `name`='Nightmare_Kraken';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =99 AND `zoneid`=41 AND `name`='Nightmare_Snoll';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =100 AND `zoneid`=41 AND `name`='Vanguard_Amputator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =101 AND `zoneid`=41 AND `name`='Vanguard_Vexer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =102 AND `zoneid`=41 AND `name`='Vanguard_Neckchopper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =103 AND `zoneid`=41 AND `name`='Vanguard_Predator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =104 AND `zoneid`=41 AND `name`='Vanguard_Impaler';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =105 AND `zoneid`=41 AND `name`='Vanguards_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =108 AND `zoneid`=41 AND `name`='Vanguard_Footsoldier';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =109 AND `zoneid`=41 AND `name`='Vanguard_Pillager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =110 AND `zoneid`=41 AND `name`='Vanguard_Trooper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =111 AND `zoneid`=41 AND `name`='Vanguard_Bugler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =112 AND `zoneid`=41 AND `name`='Vanguard_Gutslasher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =113 AND `zoneid`=41 AND `name`='Vanguard_Dollmaster';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =114 AND `zoneid`=41 AND `name`='Vanguards_Avatar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =115 AND `zoneid`=41 AND `name`='Vanguard_Grappler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =116 AND `zoneid`=41 AND `name`='Vanguard_Mesmerizer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =117 AND `zoneid`=41 AND `name`='Vanguard_Hawker';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =118 AND `zoneid`=41 AND `name`='Vanguards_Hecteyes';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =119 AND `zoneid`=41 AND `name`='Vanguard_Backstabber';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =120 AND `zoneid`=41 AND `name`='Vanguard_Alchemist';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =121 AND `zoneid`=41 AND `name`='Vanguard_Armorer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =122 AND `zoneid`=41 AND `name`='Vanguard_Pathfinder';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =123 AND `zoneid`=41 AND `name`='Vanguards_Slime';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =124 AND `zoneid`=41 AND `name`='Vanguard_Ronin';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =127 AND `zoneid`=41 AND `name`='Nightmare_Tiger';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =128 AND `zoneid`=41 AND `name`='Vanguard_Smithy';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =129 AND `zoneid`=41 AND `name`='Vanguard_Welldigger';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =130 AND `zoneid`=41 AND `name`='Vanguard_Tinkerer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =132 AND `zoneid`=41 AND `name`='Vanguard_Enchanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =133 AND `zoneid`=41 AND `name`='Vanguard_Ambusher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =134 AND `zoneid`=41 AND `name`='Vanguard_Hitman';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =135 AND `zoneid`=41 AND `name`='Vanguard_Dragontamer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =136 AND `zoneid`=41 AND `name`='Vanguard_Pitfighter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =137 AND `zoneid`=41 AND `name`='Vanguard_Shaman';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =138 AND `zoneid`=41 AND `name`='Vanguard_Maestro';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =139 AND `zoneid`=41 AND `name`='Vanguard_Necromancer';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =140 AND `zoneid`=41 AND `name`='Nightmare_Weapon';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =141 AND `zoneid`=41 AND `name`='Vanguard_Militant';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =142 AND `zoneid`=41 AND `name`='Vanguard_Thaumaturge';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =143 AND `zoneid`=41 AND `name`='Vanguard_Beasttender';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =144 AND `zoneid`=41 AND `name`='Vanguards_Scorpion';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =145 AND `zoneid`=41 AND `name`='Vanguard_Mason';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =146 AND `zoneid`=41 AND `name`='Vanguard_Hatamoto';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =149 AND `zoneid`=41 AND `name`='Vanguard_Vindicator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =150 AND `zoneid`=41 AND `name`='Vanguard_Protector';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =151 AND `zoneid`=41 AND `name`='Vanguard_Defender';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =152 AND `zoneid`=41 AND `name`='Vanguard_Kusa';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =153 AND `zoneid`=41 AND `name`='Vanguard_Undertaker';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =154 AND `zoneid`=41 AND `name`='Vanguard_Constable';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =155 AND `zoneid`=41 AND `name`='Vanguard_Purloiner';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =156 AND `zoneid`=41 AND `name`='Vanguard_Vigilante';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =157 AND `zoneid`=41 AND `name`='Vanguard_Minstrel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =158 AND `zoneid`=41 AND `name`='Vanguard_Drakekeeper';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =159 AND `zoneid`=41 AND `name`='Nightmare_Raptor';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =160 AND `zoneid`=41 AND `name`='Vanguard_Skirmisher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =161 AND `zoneid`=41 AND `name`='Vanguard_Sentinel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =162 AND `zoneid`=41 AND `name`='Vanguard_Exemplar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =163 AND `zoneid`=41 AND `name`='Vanguard_Inciter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =164 AND `zoneid`=41 AND `name`='Vanguard_Ogresoother';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =165 AND `zoneid`=41 AND `name`='Vanguards_Crow';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =168 AND `zoneid`=41 AND `name`='Vanguard_Priest';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =169 AND `zoneid`=41 AND `name`='Vanguard_Prelate';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =170 AND `zoneid`=41 AND `name`='Vanguard_Chanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =171 AND `zoneid`=41 AND `name`='Vanguard_Partisan';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =172 AND `zoneid`=41 AND `name`='Vanguard_Assassin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =173 AND `zoneid`=41 AND `name`='Vanguard_Visionary';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =174 AND `zoneid`=41 AND `name`='Vanguard_Liberator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =175 AND `zoneid`=41 AND `name`='Vanguard_Salvager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =176 AND `zoneid`=41 AND `name`='Vanguard_Persecutor';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =177 AND `zoneid`=41 AND `name`='Vanguard_Oracle';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =40 AND `zoneid`=42 AND `name`='Nightmare_Cluster';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =41 AND `zoneid`=42 AND `name`='Nightmare_Leech';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =42 AND `zoneid`=42 AND `name`='Kindred_Monk';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =43 AND `zoneid`=42 AND `name`='Kindred_Black_Mage';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =44 AND `zoneid`=42 AND `name`='Kindred_Beastmaster';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =45 AND `zoneid`=42 AND `name`='Kindreds_Vouivre';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =46 AND `zoneid`=42 AND `name`='Kindred_White_Mage';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =47 AND `zoneid`=42 AND `name`='Kindred_Dark_Knight';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =48 AND `zoneid`=42 AND `name`='Kindred_Ranger';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =49 AND `zoneid`=42 AND `name`='Kindred_Red_Mage';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =50 AND `zoneid`=42 AND `name`='Kindred_Paladin';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =51 AND `zoneid`=42 AND `name`='Kindred_Samurai';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =52 AND `zoneid`=42 AND `name`='Kindred_Warrior';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =53 AND `zoneid`=42 AND `name`='Kindred_Thief';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =54 AND `zoneid`=42 AND `name`='Kindred_Summoner';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =55 AND `zoneid`=42 AND `name`='Kindreds_Avatar';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =56 AND `zoneid`=42 AND `name`='Kindred_Bard';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =57 AND `zoneid`=42 AND `name`='Kindred_Ninja';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =58 AND `zoneid`=42 AND `name`='Kindred_Dragoon';
UPDATE `mob_groups` SET minLevel=78,maxLevel=81 WHERE `groupid` =59 AND `zoneid`=42 AND `name`='Kindreds_Wyvern';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =47 AND `zoneid`=81 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =31 AND `zoneid`=82 AND `name`='Gnoletrap';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =52 AND `zoneid`=82 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =5 AND `zoneid`=83 AND `name`='Duriumshell';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =24 AND `zoneid`=84 AND `name`='Tsetse_Fly';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =43 AND `zoneid`=84 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =44 AND `zoneid`=88 AND `name`='Drachenlizard';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =55 AND `zoneid`=88 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =16 AND `zoneid`=89 AND `name`='Feyweald_Sapling';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =52 AND `zoneid`=90 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =29 AND `zoneid`=91 AND `name`='Champion_Crawler';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =58 AND `zoneid`=91 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =21 AND `zoneid`=95 AND `name`='Hispid_Rarab';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =52 AND `zoneid`=95 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =34 AND `zoneid`=97 AND `name`='Condor';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =50 AND `zoneid`=97 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =8 AND `zoneid`=98 AND `name`='Gouger_Beetle';
UPDATE `mob_groups` SET minLevel=74,maxLevel=75 WHERE `groupid` =40 AND `zoneid`=98 AND `name`='Yilbegan';
UPDATE `mob_groups` SET minLevel=90,maxLevel=90 WHERE `groupid` =15 AND `zoneid`=130 AND `name`='Genbu';
UPDATE `mob_groups` SET minLevel=90,maxLevel=90 WHERE `groupid` =16 AND `zoneid`=130 AND `name`='Seiryu';
UPDATE `mob_groups` SET minLevel=90,maxLevel=90 WHERE `groupid` =17 AND `zoneid`=130 AND `name`='Byakko';
UPDATE `mob_groups` SET minLevel=90,maxLevel=90 WHERE `groupid` =18 AND `zoneid`=130 AND `name`='Suzaku';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =178 AND `zoneid`=134 AND `name`='Hydra_Beastmaster';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =179 AND `zoneid`=134 AND `name`='Hydras_Hound';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =180 AND `zoneid`=134 AND `name`='Hydra_Thief';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =181 AND `zoneid`=134 AND `name`='Hydra_Dark_Knight';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =183 AND `zoneid`=134 AND `name`='Hydra_Warrior';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =184 AND `zoneid`=134 AND `name`='Hydra_Bard';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =185 AND `zoneid`=134 AND `name`='Hydra_Ranger';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =186 AND `zoneid`=134 AND `name`='Hydra_White_Mage';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =187 AND `zoneid`=134 AND `name`='Hydra_Monk';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =188 AND `zoneid`=134 AND `name`='Hydra_Ninja';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =189 AND `zoneid`=134 AND `name`='Hydra_Summoner';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =190 AND `zoneid`=134 AND `name`='Hydras_Avatar';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =191 AND `zoneid`=134 AND `name`='Hydra_Black_Mage';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =192 AND `zoneid`=134 AND `name`='Hydra_Dragoon';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =193 AND `zoneid`=134 AND `name`='Hydras_Wyvern';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =194 AND `zoneid`=134 AND `name`='Hydra_Red_Mage';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =195 AND `zoneid`=134 AND `name`='Hydra_Paladin';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =196 AND `zoneid`=134 AND `name`='Hydra_Samurai';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =70 AND `zoneid`=135 AND `name`='Vanguard_Dragon';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =90 AND `zoneid`=135 AND `name`='Kindred_Warrior';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =91 AND `zoneid`=135 AND `name`='Kindred_White_Mage';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =92 AND `zoneid`=135 AND `name`='Kindred_Red_Mage';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =94 AND `zoneid`=135 AND `name`='Kindred_Monk';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =95 AND `zoneid`=135 AND `name`='Kindred_Black_Mage';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =96 AND `zoneid`=135 AND `name`='Kindred_Thief';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =97 AND `zoneid`=135 AND `name`='Kindred_Paladin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =98 AND `zoneid`=135 AND `name`='Kindred_Dark_Knight';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =99 AND `zoneid`=135 AND `name`='Kindred_Beastmaster';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =100 AND `zoneid`=135 AND `name`='Kindreds_Vouivre';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =101 AND `zoneid`=135 AND `name`='Kindred_Bard';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =102 AND `zoneid`=135 AND `name`='Kindred_Ranger';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =103 AND `zoneid`=135 AND `name`='Kindred_Samurai';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =104 AND `zoneid`=135 AND `name`='Kindred_Ninja';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =105 AND `zoneid`=135 AND `name`='Kindred_Dragoon';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =106 AND `zoneid`=135 AND `name`='Kindreds_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =107 AND `zoneid`=135 AND `name`='Kindred_Summoner';
UPDATE `mob_groups` SET minLevel=77,maxLevel=77 WHERE `groupid` =108 AND `zoneid`=135 AND `name`='Kindreds_Avatar';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =25 AND `zoneid`=153 AND `name`='Mourning_Crawler';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =26 AND `zoneid`=153 AND `name`='Snaggletooth_Peapuk';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =27 AND `zoneid`=153 AND `name`='Viseclaw';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =28 AND `zoneid`=153 AND `name`='Ancient_Goobbue';
UPDATE `mob_groups` SET minLevel=89,maxLevel=89 WHERE `groupid` =5 AND `zoneid`=154 AND `name`='Fafnir';
UPDATE `mob_groups` SET minLevel=89,maxLevel=89 WHERE `groupid` =6 AND `zoneid`=154 AND `name`='Nidhogg';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =20 AND `zoneid`=166 AND `name`='Hovering_Oculus';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =21 AND `zoneid`=166 AND `name`='Bilesucker';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =22 AND `zoneid`=166 AND `name`='Goblin_Hoodoo';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =23 AND `zoneid`=166 AND `name`='Goblin_Artificer';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =24 AND `zoneid`=166 AND `name`='Goblin_Tanner';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =25 AND `zoneid`=166 AND `name`='Goblin_Chaser';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =26 AND `zoneid`=166 AND `name`='Goblins_Bats';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =15 AND `zoneid`=167 AND `name`='Blind_Bat';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =16 AND `zoneid`=167 AND `name`='Panna_Cotta';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =17 AND `zoneid`=167 AND `name`='Nachtmahr';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =18 AND `zoneid`=167 AND `name`='Dabilla';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =19 AND `zoneid`=167 AND `name`='Wurdalak';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =24 AND `zoneid`=169 AND `name`='Blackwater_Pugil';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =25 AND `zoneid`=169 AND `name`='Plunderer_Crab';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =28 AND `zoneid`=169 AND `name`='Deviling_Bats';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =29 AND `zoneid`=169 AND `name`='Sodden_Bones';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =30 AND `zoneid`=169 AND `name`='Drowned_Bones';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =31 AND `zoneid`=169 AND `name`='Starborer';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =32 AND `zoneid`=169 AND `name`='Rapier_Scorpion';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =35 AND `zoneid`=169 AND `name`='Poroggo_Excavator';
UPDATE `mob_groups` SET minLevel=65,maxLevel=65 WHERE `groupid` =36 AND `zoneid`=169 AND `name`='Flume_Toad';
UPDATE `mob_groups` SET minLevel=32,maxLevel=32 WHERE `groupid` =18 AND `zoneid`=173 AND `name`='Lacerator';
UPDATE `mob_groups` SET minLevel=32,maxLevel=32 WHERE `groupid` =19 AND `zoneid`=173 AND `name`='Spool_Leech';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =22 AND `zoneid`=174 AND `name`='Kuftal_Delver';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =23 AND `zoneid`=174 AND `name`='Machairodus';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =16 AND `zoneid`=179 AND `name`='Kamlanaut_HTBF';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =29 AND `zoneid`=185 AND `name`='Kratzvatzs_Hecteyes';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =32 AND `zoneid`=185 AND `name`='Djokvukks_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =34 AND `zoneid`=185 AND `name`='Vanguard_Footsoldier';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =35 AND `zoneid`=185 AND `name`='Vanguard_Grappler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =36 AND `zoneid`=185 AND `name`='Vanguard_Amputator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =37 AND `zoneid`=185 AND `name`='Vanguard_Mesmerizer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =38 AND `zoneid`=185 AND `name`='Vanguard_Vexer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =39 AND `zoneid`=185 AND `name`='Vanguard_Pillager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =40 AND `zoneid`=185 AND `name`='Vanguard_Trooper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =41 AND `zoneid`=185 AND `name`='Vanguard_Neckchopper';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =42 AND `zoneid`=185 AND `name`='Vanguard_Hawker';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =43 AND `zoneid`=185 AND `name`='Vanguards_Hecteyes';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =44 AND `zoneid`=185 AND `name`='Vanguard_Bugler';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =45 AND `zoneid`=185 AND `name`='Vanguard_Predator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =46 AND `zoneid`=185 AND `name`='Vanguard_Gutslasher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =47 AND `zoneid`=185 AND `name`='Vanguard_Backstabber';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =48 AND `zoneid`=185 AND `name`='Vanguard_Impaler';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =49 AND `zoneid`=185 AND `name`='Vanguards_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =50 AND `zoneid`=185 AND `name`='Vanguard_Dollmaster';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =51 AND `zoneid`=185 AND `name`='Vanguards_Avatar';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =27 AND `zoneid`=186 AND `name`='RaGhos_Avatar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =32 AND `zoneid`=186 AND `name`='Vanguard_Vindicator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =33 AND `zoneid`=186 AND `name`='Vanguard_Militant';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =34 AND `zoneid`=186 AND `name`='Vanguard_Constable';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =35 AND `zoneid`=186 AND `name`='Vanguard_Thaumaturge';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =36 AND `zoneid`=186 AND `name`='Vanguard_Protector';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =37 AND `zoneid`=186 AND `name`='Vanguard_Defender';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =38 AND `zoneid`=186 AND `name`='Vanguard_Beasttender';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =39 AND `zoneid`=186 AND `name`='Vanguards_Scorpion';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =40 AND `zoneid`=186 AND `name`='Vanguard_Drakekeeper';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =41 AND `zoneid`=186 AND `name`='Vanguards_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =42 AND `zoneid`=186 AND `name`='Vanguard_Purloiner';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =43 AND `zoneid`=186 AND `name`='Vanguard_Vigilante';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =44 AND `zoneid`=186 AND `name`='Vanguard_Minstrel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =45 AND `zoneid`=186 AND `name`='Vanguard_Hatamoto';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =46 AND `zoneid`=186 AND `name`='Vanguard_Mason';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =47 AND `zoneid`=186 AND `name`='Vanguard_Kusa';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =48 AND `zoneid`=186 AND `name`='Vanguard_Undertaker';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =49 AND `zoneid`=186 AND `name`='Vanguards_Avatar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =51 AND `zoneid`=186 AND `name`='Vanguard_Defender';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =29 AND `zoneid`=187 AND `name`='Xuu_Bhoqas_Avatar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =34 AND `zoneid`=187 AND `name`='Vanguard_Salvager';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =35 AND `zoneid`=187 AND `name`='Vanguard_Skirmisher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =36 AND `zoneid`=187 AND `name`='Vanguard_Priest';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =37 AND `zoneid`=187 AND `name`='Vanguard_Prelate';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =38 AND `zoneid`=187 AND `name`='Vanguard_Visionary';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =39 AND `zoneid`=187 AND `name`='Vanguard_Sentinel';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =40 AND `zoneid`=187 AND `name`='Vanguard_Exemplar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =41 AND `zoneid`=187 AND `name`='Vanguard_Ogresoother';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =42 AND `zoneid`=187 AND `name`='Vanguards_Crow';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =43 AND `zoneid`=187 AND `name`='Vanguard_Inciter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =44 AND `zoneid`=187 AND `name`='Vanguard_Liberator';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =45 AND `zoneid`=187 AND `name`='Vanguard_Assassin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =46 AND `zoneid`=187 AND `name`='Vanguard_Persecutor';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =47 AND `zoneid`=187 AND `name`='Vanguard_Chanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =48 AND `zoneid`=187 AND `name`='Vanguard_Partisan';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =49 AND `zoneid`=187 AND `name`='Vanguards_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =50 AND `zoneid`=187 AND `name`='Vanguard_Oracle';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =51 AND `zoneid`=187 AND `name`='Vanguards_Avatar';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =57 AND `zoneid`=188 AND `name`='Feraloxs_Slime';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =59 AND `zoneid`=188 AND `name`='Scourquixs_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =62 AND `zoneid`=188 AND `name`='Vanguard_Smithy';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =63 AND `zoneid`=188 AND `name`='Vanguard_Pitfighter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =64 AND `zoneid`=188 AND `name`='Vanguard_Welldigger';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =65 AND `zoneid`=188 AND `name`='Vanguard_Alchemist';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =66 AND `zoneid`=188 AND `name`='Vanguard_Shaman';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =67 AND `zoneid`=188 AND `name`='Vanguard_Enchanter';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =68 AND `zoneid`=188 AND `name`='Vanguard_Tinkerer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =69 AND `zoneid`=188 AND `name`='Vanguard_Dragontamer';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =70 AND `zoneid`=188 AND `name`='Vanguards_Wyvern';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =71 AND `zoneid`=188 AND `name`='Vanguard_Pathfinder';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =72 AND `zoneid`=188 AND `name`='Vanguards_Slime';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =73 AND `zoneid`=188 AND `name`='Vanguard_Maestro';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =74 AND `zoneid`=188 AND `name`='Vanguard_Ronin';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =75 AND `zoneid`=188 AND `name`='Vanguard_Armorer';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =76 AND `zoneid`=188 AND `name`='Vanguard_Necromancer';
UPDATE `mob_groups` SET minLevel=75,maxLevel=75 WHERE `groupid` =77 AND `zoneid`=188 AND `name`='Vanguards_Avatar';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =78 AND `zoneid`=188 AND `name`='Vanguard_Ambusher';
UPDATE `mob_groups` SET minLevel=77,maxLevel=79 WHERE `groupid` =79 AND `zoneid`=188 AND `name`='Vanguard_Hitman';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =19 AND `zoneid`=191 AND `name`='Goblin_Brigand';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =20 AND `zoneid`=191 AND `name`='Goblin_Headsman';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =21 AND `zoneid`=191 AND `name`='Goblin_Healer';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =22 AND `zoneid`=191 AND `name`='Witchetty_Grub';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =23 AND `zoneid`=191 AND `name`='Couloir_Leech';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =24 AND `zoneid`=191 AND `name`='Prim_Pika';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =25 AND `zoneid`=191 AND `name`='Natty_Gibbon';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =26 AND `zoneid`=191 AND `name`='Trimmer';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =27 AND `zoneid`=191 AND `name`='Fume_Lizard';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =28 AND `zoneid`=191 AND `name`='Goblin_Conjurer';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =29 AND `zoneid`=191 AND `name`='Goblin_Bladesmith';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =30 AND `zoneid`=191 AND `name`='Goblin_Bushwhacker';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =6 AND `zoneid`=192 AND `name`='Troika_Bats';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =7 AND `zoneid`=192 AND `name`='Deathwatch_Beetle';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =8 AND `zoneid`=192 AND `name`='Goblin_Flesher';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =9 AND `zoneid`=192 AND `name`='Goblin_Metallurgist';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =10 AND `zoneid`=192 AND `name`='Goblin_Lurcher';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =11 AND `zoneid`=192 AND `name`='Skinnymalinks';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =12 AND `zoneid`=192 AND `name`='Skinnymajinx';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =13 AND `zoneid`=192 AND `name`='Covin_Bat';
UPDATE `mob_groups` SET minLevel=25,maxLevel=25 WHERE `groupid` =14 AND `zoneid`=192 AND `name`='Goblin_Trailblazer';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =18 AND `zoneid`=193 AND `name`='Buds_Bunny';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =19 AND `zoneid`=193 AND `name`='Bilis_Leech';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =24 AND `zoneid`=193 AND `name`='Swagger_Spruce';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =25 AND `zoneid`=193 AND `name`='Targe_Beetle';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =8 AND `zoneid`=194 AND `name`='Fetor_Bats';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =9 AND `zoneid`=194 AND `name`='Fuligo';
UPDATE `mob_groups` SET minLevel=35,maxLevel=35 WHERE `groupid` =14 AND `zoneid`=194 AND `name`='Thorn_Bat';
UPDATE `mob_groups` SET minLevel=57,maxLevel=57 WHERE `groupid` =15 AND `zoneid`=195 AND `name`='Hellbound_Warrior';
UPDATE `mob_groups` SET minLevel=57,maxLevel=57 WHERE `groupid` =16 AND `zoneid`=195 AND `name`='Hellbound_Warlock';
UPDATE `mob_groups` SET minLevel=57,maxLevel=57 WHERE `groupid` =32 AND `zoneid`=195 AND `name`='Nekros_Hound';
UPDATE `mob_groups` SET minLevel=60,maxLevel=60 WHERE `groupid` =16 AND `zoneid`=197 AND `name`='King_Crawler';
UPDATE `mob_groups` SET minLevel=60,maxLevel=60 WHERE `groupid` =17 AND `zoneid`=197 AND `name`='Vespo';
UPDATE `mob_groups` SET minLevel=60,maxLevel=60 WHERE `groupid` =18 AND `zoneid`=197 AND `name`='Dancing_Jewel';
UPDATE `mob_groups` SET minLevel=60,maxLevel=60 WHERE `groupid` =19 AND `zoneid`=197 AND `name`='Olid_Funguar';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =18 AND `zoneid`=198 AND `name`='Bleeder_Leech';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =21 AND `zoneid`=198 AND `name`='Chaser_Bats';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =22 AND `zoneid`=198 AND `name`='Crypterpillar';
UPDATE `mob_groups` SET minLevel=33,maxLevel=33 WHERE `groupid` =23 AND `zoneid`=198 AND `name`='Warren_Bat';
UPDATE `mob_groups` SET minLevel=40,maxLevel=40 WHERE `groupid` =15 AND `zoneid`=200 AND `name`='Fortalice_Bats';
UPDATE `mob_groups` SET minLevel=41,maxLevel=41 WHERE `groupid` =29 AND `zoneid`=200 AND `name`='Kaboom';
UPDATE `mob_groups` SET minLevel=41,maxLevel=41 WHERE `groupid` =35 AND `zoneid`=200 AND `name`='Warden_Beetle';
UPDATE `mob_groups` SET minLevel=41,maxLevel=41 WHERE `groupid` =40 AND `zoneid`=200 AND `name`='Donjon_Bat';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =7 AND `zoneid`=201 AND `name`='Garuda_Prime_HTBF';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =8 AND `zoneid`=202 AND `name`='Ramuh_Prime_HTBF';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =7 AND `zoneid`=203 AND `name`='Shiva_Prime_HTBF';
UPDATE `mob_groups` SET minLevel=58,maxLevel=58 WHERE `groupid` =16 AND `zoneid`=204 AND `name`='Wekufe';
UPDATE `mob_groups` SET minLevel=58,maxLevel=58 WHERE `groupid` =17 AND `zoneid`=204 AND `name`='Sentient_Carafe';
UPDATE `mob_groups` SET minLevel=58,maxLevel=58 WHERE `groupid` =18 AND `zoneid`=204 AND `name`='Balayang';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =6 AND `zoneid`=207 AND `name`='Ifrit_Prime_HTBF';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =7 AND `zoneid`=209 AND `name`='Titan_Prime_HTBF';
UPDATE `mob_groups` SET minLevel=94,maxLevel=94 WHERE `groupid` =6 AND `zoneid`=211 AND `name`='Leviathan_Prime_HTBF';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =20 AND `zoneid`=212 AND `name`='Boulder_Eater';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =21 AND `zoneid`=212 AND `name`='Pygmytoise';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =31 AND `zoneid`=213 AND `name`='Babaulas';
UPDATE `mob_groups` SET minLevel=78,maxLevel=78 WHERE `groupid` =32 AND `zoneid`=213 AND `name`='Boribaba';

-- Escha Zi'Tah EXP Camps
UPDATE `mob_groups` SET minLevel = "70", maxLevel = "75" WHERE name = "Eschan_Vulture";
UPDATE `mob_groups` SET minLevel = "70", maxLevel = "75" WHERE name = "Eschan_Warrior";
UPDATE `mob_groups` SET minLevel = "70", maxLevel = "75" WHERE name = "Eschan_Corse";
UPDATE `mob_groups` SET minLevel = "70", maxLevel = "75" WHERE name = "Eschan_Sorcerer";
UPDATE `mob_groups` SET minLevel = "75", maxLevel = "80" WHERE name = "Eschan_Wasp";
UPDATE `mob_groups` SET minLevel = "75", maxLevel = "80" WHERE name = "Eschan_Snapweed";
UPDATE `mob_groups` SET minLevel = "75", maxLevel = "80" WHERE name = "Eschan_Goobbue";
UPDATE `mob_groups` SET minLevel = "80", maxLevel = "84" WHERE name = "Eschan_Puk";
UPDATE `mob_groups` SET minLevel = "80", maxLevel = "84" WHERE name = "Eschan_Shadow_Dragon";
UPDATE `mob_groups` SET minLevel = "80", maxLevel = "84" WHERE name = "Eschan_Tarichuk";
UPDATE `mob_groups` SET minLevel = "80", maxLevel = "84" WHERE name = "Eschan_Bugard";
UPDATE `mob_groups` SET minLevel = "80", maxLevel = "84" WHERE name = "Eschan_Opo-Opo";
UPDATE `mob_groups` SET minLevel = "80", maxLevel = "84" WHERE name = "Eschan_Yztarg";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Mosquito";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Jewelweed";

-- Escha RuAun
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Zdei";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_rng";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_thf";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_blm";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaerns_Wynav";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_drg";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Phuabo";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_war";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Yovra";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_whm";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_mnk";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_bst";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaerns_Euvhi";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Euvhi";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Clionid";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Hpemde";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_pld";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Amoeban";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_drk";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Xzomit";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_rdm";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Murex";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_sam";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_smn";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaerns_Spirit";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ghrah";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Limule";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Gargouille";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Porxie";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_brd";
UPDATE `mob_groups` SET minLevel = "78", maxLevel = "80" WHERE name = "Eschan_Ilaern_nin";

-- Set Escha mobs to aggro
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "4652"; -- Eschan_Snapweed
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "4848"; -- Eschan_Puk
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "4849"; -- Eschan_Opo-Opo
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5349"; -- Eschan_Coeurl
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5350"; -- Eschan_Dhalmel
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5365"; -- Eschan_Yztarg
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5429"; -- Eschan_Jewelweed
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5538"; -- Eschan_Worm
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5539"; -- Eschan_Wasp
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5540"; -- Eschan_Goobbue
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5541"; -- Eschan_Shadow_Dragon
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5542"; -- Eschan_Tarichuk
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5543"; -- Eschan_Mosquito
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "6317"; -- Eschan_Crawler
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "6406"; -- Eschan_Obdella
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "6446"; -- Eschan_Vulture
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "6482"; -- Eschan_Corse
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "6553"; -- Eschan_Warrior
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "6569"; -- Eschan_Sorcerer
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "6591"; -- Eschan_Weapon
-- UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5637"; -- Eschan_Bugard
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5620"; -- Eschan_Limule
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5621"; -- Eschan_Murex
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5622"; -- Eschan_Amoeban
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5623"; -- Eschan_Clionid
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5625"; -- Eschan_Zdei
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5626"; -- Eschan_Phuabo
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5627"; -- Eschan_Ghrah
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5628"; -- Eschan_Xzomit
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5629"; -- Eschan_Hpemde
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5630"; -- Eschan_Euvhi
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5632"; -- Eschan_Porxie
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5650"; -- Eschan_Gargouille
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5651"; -- Eschan_Ilaerns_Wynav
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5652"; -- Eschan_Ilaerns_Euvhi
UPDATE `mob_pools` SET aggro = "1" WHERE poolid = "5653"; -- Eschan_Ilaerns_Spirit
