# Change and save your Dbtool.py default protected list by editing this file.

# These are the 'protected' files
player_data = [
    'accounts.sql',
    'accounts_banned.sql',
    'auction_house.sql',
    'char_blacklist.sql',
    'char_effects.sql',
    'char_equip.sql',
    'char_exp.sql',
    'char_history.sql',
    'char_inventory.sql',
    'char_jobs.sql',
    'char_job_points.sql',
    'char_look.sql',
    'char_merit.sql',
    'char_pet.sql',
    'char_points.sql',
    'char_profile.sql',
    'char_skills.sql',
    'char_spells.sql',
    'char_stats.sql',
    'char_storage.sql',
    'char_style.sql',
    'char_unlocks.sql',
    'char_vars.sql',
    'chars.sql',
    'conquest_system.sql',
    'delivery_box.sql',
    'linkshells.sql',
    'server_variables.sql',
    'unity_system.sql',
]